//
// UIColor+Crayola.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
// Created by Mihaela Mihaljević Jakić
//
//

#import "UIColor+Crayola.h"

@implementation UIColor (Crayola)

+(UIColor *)crayola_Dandelion_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.858824 blue:0.427451 alpha:1.0];
};

+(UIColor *)crayola_MangoTango_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.509804 blue:0.262745 alpha:1.0];
};

+(UIColor *)crayola_PineGreen_Color 
{
	return [UIColor colorWithRed:0.082353 green:0.501961 blue:0.470588 alpha:1.0];
};

+(UIColor *)crayola_OrangeRed_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.168627 blue:0.168627 alpha:1.0];
};

+(UIColor *)crayola_WildStrawberry_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.262745 blue:0.643137 alpha:1.0];
};

+(UIColor *)crayola_Cornflower_Color 
{
	return [UIColor colorWithRed:0.603922 green:0.807843 blue:0.921569 alpha:1.0];
};

+(UIColor *)crayola_AtomicTangerine_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.643137 blue:0.454902 alpha:1.0];
};

+(UIColor *)crayola_CottonCandy_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.737255 blue:0.850980 alpha:1.0];
};

+(UIColor *)crayola_Sunglow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.811765 blue:0.282353 alpha:1.0];
};

+(UIColor *)crayola_BlueViolet_Color 
{
	return [UIColor colorWithRed:0.450980 green:0.400000 blue:0.741176 alpha:1.0];
};

+(UIColor *)crayola_Manatee_Color 
{
	return [UIColor colorWithRed:0.592157 green:0.603922 blue:0.666667 alpha:1.0];
};

+(UIColor *)crayola_GreenBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.392157 blue:0.705882 alpha:1.0];
};

+(UIColor *)crayola_WildWatermelon_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.423529 blue:0.521569 alpha:1.0];
};

+(UIColor *)crayola_PurplePizzazz_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.305882 blue:0.854902 alpha:1.0];
};

+(UIColor *)crayola_VioletBlue_Color 
{
	return [UIColor colorWithRed:0.196078 green:0.290196 blue:0.698039 alpha:1.0];
};

+(UIColor *)crayola_Cerulean_Color 
{
	return [UIColor colorWithRed:0.113725 green:0.674510 blue:0.839216 alpha:1.0];
};

+(UIColor *)crayola_SpringGreen_Color 
{
	return [UIColor colorWithRed:0.925490 green:0.917647 blue:0.745098 alpha:1.0];
};

+(UIColor *)crayola_BurntOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.498039 blue:0.286275 alpha:1.0];
};

+(UIColor *)crayola_Orchid_Color 
{
	return [UIColor colorWithRed:0.901961 green:0.658824 blue:0.843137 alpha:1.0];
};

+(UIColor *)crayola_BlizzardBlue_Color 
{
	return [UIColor colorWithRed:0.674510 green:0.898039 blue:0.933333 alpha:1.0];
};

+(UIColor *)crayola_OrangeYellow_Color 
{
	return [UIColor colorWithRed:0.972549 green:0.835294 blue:0.407843 alpha:1.0];
};

+(UIColor *)crayola_Aquamarine_Color 
{
	return [UIColor colorWithRed:0.470588 green:0.858824 blue:0.886275 alpha:1.0];
};

+(UIColor *)crayola_Magenta_Color 
{
	return [UIColor colorWithRed:0.964706 green:0.392157 blue:0.686275 alpha:1.0];
};

+(UIColor *)crayola_RawUmber_Color 
{
	return [UIColor colorWithRed:0.443137 green:0.294118 blue:0.137255 alpha:1.0];
};

+(UIColor *)crayola_LaserLemon_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.996078 blue:0.133333 alpha:1.0];
};

+(UIColor *)crayola_GrannySmithApple_Color 
{
	return [UIColor colorWithRed:0.658824 green:0.894118 blue:0.627451 alpha:1.0];
};

+(UIColor *)crayola_SeaGreen_Color 
{
	return [UIColor colorWithRed:0.576471 green:0.874510 blue:0.721569 alpha:1.0];
};

+(UIColor *)crayola_UnmellowYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)crayola_Maize_Color 
{
	return [UIColor colorWithRed:0.929412 green:0.819608 blue:0.611765 alpha:1.0];
};

+(UIColor *)crayola_RawSienna_Color 
{
	return [UIColor colorWithRed:0.839216 green:0.541176 blue:0.349020 alpha:1.0];
};

+(UIColor *)crayola_PiggyPink_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.866667 blue:0.901961 alpha:1.0];
};

+(UIColor *)crayola_YellowOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.682353 blue:0.258824 alpha:1.0];
};

+(UIColor *)crayola_PurpleMountainsMajesty_Color 
{
	return [UIColor colorWithRed:0.615686 green:0.505882 blue:0.729412 alpha:1.0];
};

+(UIColor *)crayola_Mauvelous_Color 
{
	return [UIColor colorWithRed:0.937255 green:0.596078 blue:0.666667 alpha:1.0];
};

+(UIColor *)crayola_MidnightBlue_Color 
{
	return [UIColor colorWithRed:0.101961 green:0.282353 blue:0.462745 alpha:1.0];
};

+(UIColor *)crayola_LemonYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.956863 blue:0.309804 alpha:1.0];
};

+(UIColor *)crayola_VividTangerine_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.627451 blue:0.537255 alpha:1.0];
};

+(UIColor *)crayola_Razzmatazz_Color 
{
	return [UIColor colorWithRed:0.890196 green:0.145098 blue:0.419608 alpha:1.0];
};

+(UIColor *)crayola_TealBlue_Color 
{
	return [UIColor colorWithRed:0.094118 green:0.654902 blue:0.709804 alpha:1.0];
};

+(UIColor *)crayola_Shadow_Color 
{
	return [UIColor colorWithRed:0.541176 green:0.474510 blue:0.364706 alpha:1.0];
};

+(UIColor *)crayola_Gold_Color 
{
	return [UIColor colorWithRed:0.905882 green:0.776471 blue:0.592157 alpha:1.0];
};

+(UIColor *)crayola_Blush_Color 
{
	return [UIColor colorWithRed:0.870588 green:0.364706 blue:0.513726 alpha:1.0];
};

+(UIColor *)crayola_RazzleDazzleRose_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.282353 blue:0.815686 alpha:1.0];
};

+(UIColor *)crayola_Indigo_Color 
{
	return [UIColor colorWithRed:0.364706 green:0.462745 blue:0.796078 alpha:1.0];
};

+(UIColor *)crayola_ForestGreen_Color 
{
	return [UIColor colorWithRed:0.427451 green:0.682353 blue:0.505882 alpha:1.0];
};

+(UIColor *)crayola_Orange_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.458824 blue:0.219608 alpha:1.0];
};

+(UIColor *)crayola_Red_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.125490 blue:0.301961 alpha:1.0];
};

+(UIColor *)crayola_Silver_Color 
{
	return [UIColor colorWithRed:0.803922 green:0.772549 blue:0.760784 alpha:1.0];
};

+(UIColor *)crayola_Inchworm_Color 
{
	return [UIColor colorWithRed:0.698039 green:0.925490 blue:0.364706 alpha:1.0];
};

+(UIColor *)crayola_CarnationPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.800000 alpha:1.0];
};

+(UIColor *)crayola_Fern_Color 
{
	return [UIColor colorWithRed:0.443137 green:0.737255 blue:0.470588 alpha:1.0];
};

+(UIColor *)crayola_RoyalPurple_Color 
{
	return [UIColor colorWithRed:0.470588 green:0.317647 blue:0.662745 alpha:1.0];
};

+(UIColor *)crayola_Black_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)crayola_RedOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.325490 blue:0.286275 alpha:1.0];
};

+(UIColor *)crayola_Plum_Color 
{
	return [UIColor colorWithRed:0.556863 green:0.270588 blue:0.521569 alpha:1.0];
};

+(UIColor *)crayola_Mahogany_Color 
{
	return [UIColor colorWithRed:0.803922 green:0.290196 blue:0.298039 alpha:1.0];
};

+(UIColor *)crayola_Tan_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.654902 blue:0.423529 alpha:1.0];
};

+(UIColor *)crayola_FuzzyWuzzy_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.400000 blue:0.400000 alpha:1.0];
};

+(UIColor *)crayola_Beaver_Color 
{
	return [UIColor colorWithRed:0.623529 green:0.505882 blue:0.439216 alpha:1.0];
};

+(UIColor *)crayola_BananaMania_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.905882 blue:0.709804 alpha:1.0];
};

+(UIColor *)crayola_WildBlueYonder_Color 
{
	return [UIColor colorWithRed:0.635294 green:0.678431 blue:0.815686 alpha:1.0];
};

+(UIColor *)crayola_NeonCarrot_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.639216 blue:0.262745 alpha:1.0];
};

+(UIColor *)crayola_Shamrock_Color 
{
	return [UIColor colorWithRed:0.270588 green:0.807843 blue:0.635294 alpha:1.0];
};

+(UIColor *)crayola_JungleGreen_Color 
{
	return [UIColor colorWithRed:0.231373 green:0.690196 blue:0.560784 alpha:1.0];
};

+(UIColor *)crayola_Canary_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)crayola_HotMagenta_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.113725 blue:0.807843 alpha:1.0];
};

+(UIColor *)crayola_Melon_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.737255 blue:0.705882 alpha:1.0];
};

+(UIColor *)crayola_MacaroniandCheese_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.741176 blue:0.533333 alpha:1.0];
};

+(UIColor *)crayola_Tumbleweed_Color 
{
	return [UIColor colorWithRed:0.870588 green:0.666667 blue:0.533333 alpha:1.0];
};

+(UIColor *)crayola_Timberwolf_Color 
{
	return [UIColor colorWithRed:0.858824 green:0.843137 blue:0.823529 alpha:1.0];
};

+(UIColor *)crayola_White_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)crayola_TickleMePink_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.537255 blue:0.674510 alpha:1.0];
};

+(UIColor *)crayola_SkyBlue_Color 
{
	return [UIColor colorWithRed:0.501961 green:0.854902 blue:0.921569 alpha:1.0];
};

+(UIColor *)crayola_Scarlet_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.156863 blue:0.278431 alpha:1.0];
};

+(UIColor *)crayola_Almond_Color 
{
	return [UIColor colorWithRed:0.937255 green:0.870588 blue:0.803922 alpha:1.0];
};

+(UIColor *)crayola_Fuchsia_Color 
{
	return [UIColor colorWithRed:0.764706 green:0.392157 blue:0.772549 alpha:1.0];
};

+(UIColor *)crayola_OutrageousOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.431373 blue:0.290196 alpha:1.0];
};

+(UIColor *)crayola_PacificBlue_Color 
{
	return [UIColor colorWithRed:0.109804 green:0.662745 blue:0.788235 alpha:1.0];
};

+(UIColor *)crayola_Copper_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.580392 blue:0.458824 alpha:1.0];
};

+(UIColor *)crayola_Blue_Color 
{
	return [UIColor colorWithRed:0.121569 green:0.458824 blue:0.996078 alpha:1.0];
};

+(UIColor *)crayola_Gray_Color 
{
	return [UIColor colorWithRed:0.584314 green:0.568627 blue:0.549020 alpha:1.0];
};

+(UIColor *)crayola_Bittersweet_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.486275 blue:0.431373 alpha:1.0];
};

+(UIColor *)crayola_RadicalRed_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.286275 blue:0.423529 alpha:1.0];
};

+(UIColor *)crayola_PurpleHeart_Color 
{
	return [UIColor colorWithRed:0.454902 green:0.258824 blue:0.784314 alpha:1.0];
};

+(UIColor *)crayola_PinkFlamingo_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.454902 blue:0.992157 alpha:1.0];
};

+(UIColor *)crayola_Denim_Color 
{
	return [UIColor colorWithRed:0.168627 green:0.423529 blue:0.768627 alpha:1.0];
};

+(UIColor *)crayola_Chestnut_Color 
{
	return [UIColor colorWithRed:0.737255 green:0.364706 blue:0.345098 alpha:1.0];
};

+(UIColor *)crayola_Goldenrod_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.850980 blue:0.458824 alpha:1.0];
};

+(UIColor *)crayola_RobinsEggBlue_Color 
{
	return [UIColor colorWithRed:0.121569 green:0.807843 blue:0.796078 alpha:1.0];
};

+(UIColor *)crayola_TropicalRainForest_Color 
{
	return [UIColor colorWithRed:0.090196 green:0.501961 blue:0.427451 alpha:1.0];
};

+(UIColor *)crayola_CaribbeanGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.800000 blue:0.600000 alpha:1.0];
};

+(UIColor *)crayola_BrickRed_Color 
{
	return [UIColor colorWithRed:0.796078 green:0.254902 blue:0.329412 alpha:1.0];
};

+(UIColor *)crayola_Yellow_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.909804 blue:0.513726 alpha:1.0];
};

+(UIColor *)crayola_ScreaminGreen_Color 
{
	return [UIColor colorWithRed:0.462745 green:1.000000 blue:0.478431 alpha:1.0];
};

+(UIColor *)crayola_Asparagus_Color 
{
	return [UIColor colorWithRed:0.529412 green:0.662745 blue:0.419608 alpha:1.0];
};

+(UIColor *)crayola_BlueBell_Color 
{
	return [UIColor colorWithRed:0.635294 green:0.635294 blue:0.815686 alpha:1.0];
};

+(UIColor *)crayola_JazzberryJam_Color 
{
	return [UIColor colorWithRed:0.792157 green:0.215686 blue:0.403922 alpha:1.0];
};

+(UIColor *)crayola_VioletRed_Color 
{
	return [UIColor colorWithRed:0.968627 green:0.325490 blue:0.580392 alpha:1.0];
};

+(UIColor *)crayola_Apricot_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.850980 blue:0.709804 alpha:1.0];
};

+(UIColor *)crayola_SunsetOrange_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.368627 blue:0.325490 alpha:1.0];
};

+(UIColor *)crayola_YellowGreen_Color 
{
	return [UIColor colorWithRed:0.772549 green:0.890196 blue:0.517647 alpha:1.0];
};

+(UIColor *)crayola_Lavender_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.705882 blue:0.835294 alpha:1.0];
};

+(UIColor *)crayola_BlueGreen_Color 
{
	return [UIColor colorWithRed:0.050980 green:0.596078 blue:0.729412 alpha:1.0];
};

+(UIColor *)crayola_BurntSienna_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.494118 blue:0.364706 alpha:1.0];
};

+(UIColor *)crayola_Thistle_Color 
{
	return [UIColor colorWithRed:0.921569 green:0.780392 blue:0.874510 alpha:1.0];
};

+(UIColor *)crayola_NavyBlue_Color 
{
	return [UIColor colorWithRed:0.098039 green:0.454902 blue:0.823529 alpha:1.0];
};

+(UIColor *)crayola_Brown_Color 
{
	return [UIColor colorWithRed:0.705882 green:0.403922 blue:0.301961 alpha:1.0];
};

+(UIColor *)crayola_VioletPurple_Color 
{
	return [UIColor colorWithRed:0.572549 green:0.431373 blue:0.682353 alpha:1.0];
};

+(UIColor *)crayola_OuterSpace_Color 
{
	return [UIColor colorWithRed:0.254902 green:0.290196 blue:0.298039 alpha:1.0];
};

+(UIColor *)crayola_ShockingPink_Color 
{
	return [UIColor colorWithRed:0.984314 green:0.494118 blue:0.992157 alpha:1.0];
};

+(UIColor *)crayola_MountainMeadow_Color 
{
	return [UIColor colorWithRed:0.188235 green:0.729412 blue:0.560784 alpha:1.0];
};

+(UIColor *)crayola_Salmon_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.607843 blue:0.666667 alpha:1.0];
};

+(UIColor *)crayola_AntiqueBrass_Color 
{
	return [UIColor colorWithRed:0.803922 green:0.584314 blue:0.458824 alpha:1.0];
};

+(UIColor *)crayola_Cerise_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.266667 blue:0.572549 alpha:1.0];
};

+(UIColor *)crayola_Maroon_Color 
{
	return [UIColor colorWithRed:0.784314 green:0.219608 blue:0.352941 alpha:1.0];
};

+(UIColor *)crayola_PinkSherbert_Color 
{
	return [UIColor colorWithRed:0.968627 green:0.560784 blue:0.654902 alpha:1.0];
};

+(UIColor *)crayola_DesertSand_Color 
{
	return [UIColor colorWithRed:0.937255 green:0.803922 blue:0.721569 alpha:1.0];
};

+(UIColor *)crayola_Green_Color 
{
	return [UIColor colorWithRed:0.109804 green:0.674510 blue:0.470588 alpha:1.0];
};

+(UIColor *)crayola_Sepia_Color 
{
	return [UIColor colorWithRed:0.647059 green:0.411765 blue:0.309804 alpha:1.0];
};

+(UIColor *)crayola_Periwinkle_Color 
{
	return [UIColor colorWithRed:0.772549 green:0.815686 blue:0.901961 alpha:1.0];
};

+(UIColor *)crayola_TurquoiseBlue_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.866667 blue:0.905882 alpha:1.0];
};

+(UIColor *)crayola_MagicMint_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.941176 blue:0.819608 alpha:1.0];
};

+(UIColor *)crayola_Peach_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.811765 blue:0.670588 alpha:1.0];
};

+(UIColor *)crayola_RedViolet_Color 
{
	return [UIColor colorWithRed:0.752941 green:0.266667 blue:0.560784 alpha:1.0];
};

+(UIColor *)crayola_ElectricLime_Color 
{
	return [UIColor colorWithRed:0.807843 green:1.000000 blue:0.113725 alpha:1.0];
};

+(UIColor *)crayola_Mulberry_Color 
{
	return [UIColor colorWithRed:0.772549 green:0.294118 blue:0.549020 alpha:1.0];
};

+(UIColor *)crayola_BlueGray_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.800000 alpha:1.0];
};

+(UIColor *)crayola_Eggplant_Color 
{
	return [UIColor colorWithRed:0.431373 green:0.317647 blue:0.376471 alpha:1.0];
};

+(UIColor *)crayola_Wisteria_Color 
{
	return [UIColor colorWithRed:0.803922 green:0.643137 blue:0.870588 alpha:1.0];
};

+(UIColor *)crayola_VividViolet_Color 
{
	return [UIColor colorWithRed:0.560784 green:0.313726 blue:0.615686 alpha:1.0];
};

+(UIColor *)crayola_CadetBlue_Color 
{
	return [UIColor colorWithRed:0.690196 green:0.717647 blue:0.776471 alpha:1.0];
};

+(UIColor *)crayola_GreenYellow_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.909804 blue:0.568627 alpha:1.0];
};

+(UIColor *)crayola_OliveGreen_Color 
{
	return [UIColor colorWithRed:0.729412 green:0.721569 blue:0.423529 alpha:1.0];
};

@end