//
// UIColor+HTML.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
//
//

#import "UIColor+HTML.h"

@implementation UIColor (HTML)

+(UIColor *)HTML_gray84_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.400000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_DarkOrange1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_SpringGreen3_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_salmon1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LavenderBlush4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_SteelBlue_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.400000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_burlywood1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_gold2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray56_Color 
{
	return [UIColor colorWithRed:0.533333 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_DarkSlateGray2_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.866667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_goldenrod3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_DarkTurquoise_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_pink3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_MintCream_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray60_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.600000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_bisque3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray28_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.466667 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_PaleTurquoise1_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.733333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_orchid4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_sienna1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_turquoise3_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray32_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.133333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_chartreuse2_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.400000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gold3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_pink4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_brown2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_OrangeRed4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_medium_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray85_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.600000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_snow1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LemonChiffon3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_DarkGoldenrod4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_goldenrod2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray57_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.066667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_gold4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_AliceBlue_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.200000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_ivory1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_MediumPurple2_Color 
{
	return [UIColor colorWithRed:0.600000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_MediumSlateBlue_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray61_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.800000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_PaleGreen_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.533333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_IndianRed_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_snow2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_DarkSlateGray3_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.600000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray29_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.666667 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_purple1_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.733333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_RosyBrown4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_turquoise2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray33_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.266667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_orange3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LightSteelBlue3_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.133333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_PaleTurquoise2_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_brown3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_OrangeRed3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_SlateGray4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.800000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_gray2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.333333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_OldLace_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_NavyBlue_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_LightSalmon4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_gray86_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.733333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_snow3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_salmon2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_black_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray90_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.333333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_thistle1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_goldenrod1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_CadetBlue4_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.200000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray58_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.266667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_DarkSlateBlue_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.533333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_PaleVioletRed1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_ivory2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_MediumSpringGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LightSteelBlue_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray62_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.933333 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_beige_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray3_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.533333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_bisque4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_SlateBlue4_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.466667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_snow4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_cyan1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_RosyBrown3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_turquoise1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_sienna2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_cornsilk4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_MediumPurple4_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.866667 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_SkyBlue3_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.800000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_chartreuse1_Color 
{
	return [UIColor colorWithRed:0.466667 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray34_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.466667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_aquamarine2_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.400000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_DarkSlateGray4_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.133333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_OrangeRed2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_SlateGray3_Color 
{
	return [UIColor colorWithRed:0.600000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_brown4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_DeepSkyBlue4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.666667 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_maroon_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_PaleTurquoise3_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.400000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray87_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_salmon_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_cyan2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_SandyBrown_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.266667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_gray10_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.666667 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_CadetBlue3_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.666667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray91_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.533333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_BlueViolet_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.666667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_gray59_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.400000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_ivory3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_LightPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray5_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.866667 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray63_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.066667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_SlateBlue3_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_RosyBrown2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_cornsilk2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_PaleVioletRed2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_cyan3_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_PeachPuff4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_purple2_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.066667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_gray35_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.600000 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_DarkOliveGreen1_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_orange4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_OrangeRed1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_SlateGray2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.600000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_HotPink1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_LightPink4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_SeaGreen4_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.933333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_NavajoWhite4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_VioletRed_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.000000 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_gray6_Color 
{
	return [UIColor colorWithRed:0.000000 green:1.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_SpringGreen2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_MediumOrchid2_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.066667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_GreenYellow_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.866667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray88_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_magenta2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_cyan4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_salmon3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_DimGray_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_CadetBlue2_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_AntiqueWhite2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_gray11_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.800000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray92_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.733333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_LightSteelBlue4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.933333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_LightYellow4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_PaleTurquoise4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LightSkyBlue_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_LightCoral_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_SlateBlue2_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.666667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_GhostWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.533333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_ivory4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_honeydew4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.200000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray7_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.133333 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray64_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.200000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_RosyBrown1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_DarkOrchid4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.533333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_PeachPuff3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_sienna3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_DarkOrchid_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.600000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_PaleGreen4_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.266667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_aquamarine1_Color 
{
	return [UIColor colorWithRed:0.466667 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray36_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.800000 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_SlateGray1_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.400000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_VioletRed4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_LightPink3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_maroon1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_PaleVioletRed3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_SeaGreen2_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray40_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray8_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.266667 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray89_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.200000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_CadetBlue1_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.533333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_pink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray12_Color 
{
	return [UIColor colorWithRed:0.066667 green:1.000000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray93_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.866667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_MediumOrchid4_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.666667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_SlateBlue1_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.200000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_chocolate_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.133333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_blue1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_honeydew2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_AntiqueWhite4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_firebrick_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.133333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_gray9_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.466667 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray65_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.400000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_LightSkyBlue2_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.266667 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_PeachPuff2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_PaleGreen3_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.800000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_goldenrod_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.666667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_purple3_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.866667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_VioletRed3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_gray37_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.933333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_MediumOrchid_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.666667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_LightPink2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_RosyBrown_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.800000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LightSalmon3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_blue2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray41_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_DeepPink3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_PaleVioletRed4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_salmon4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_white_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray13_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.066667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_plum_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_DarkOliveGreen2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.800000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray94_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_thistle2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_LightGray_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.200000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_red1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_DodgerBlue4_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_SteelBlue4_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.400000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray66_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.533333 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_DarkOrchid3_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.666667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_PeachPuff1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_PaleGreen2_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_red2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_sienna4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_gray70_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.200000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_SkyBlue4_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.666667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_VioletRed2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_OliveDrab4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_khaki1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LightPink1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_DeepSkyBlue3_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_gray38_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.066667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_LightSkyBlue4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_maroon2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_red3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_DeepPink1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_DarkSeaGreen2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.266667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_blue4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray42_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_LightBlue4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.533333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_red4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray14_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.266667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_gray95_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.133333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_seashell3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_moccasin_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_azure1_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_SteelBlue3_Color 
{
	return [UIColor colorWithRed:0.266667 green:1.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_DarkSlateGray_Color 
{
	return [UIColor colorWithRed:0.133333 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_thistle_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.533333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray67_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.733333 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_PaleGreen1_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_purple4_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.333333 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_pale_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_VioletRed1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_gray71_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.333333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_khaki2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray39_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.200000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_NavajoWhite3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_PaleVioletRed_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_HotPink2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_SpringGreen1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray43_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.933333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_magenta3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_LightBlue3_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.666667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_PaleGoldenrod_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_DarkSeaGreen4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray15_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.400000 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_LightYellow3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_seashell1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_yellow1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LightGoldenrod1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_SteelBlue2_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.800000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_DodgerBlue3_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.533333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_azure2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_tomato1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_DarkOrchid2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.133333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_gray68_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_DarkViolet_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.266667 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_RoyalBlue4_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.466667 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_ForestGreen_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.133333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_OliveDrab2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.200000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray72_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.533333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_DarkOliveGreen3_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.133333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_khaki3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_maroon3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_PaleTurquoise_Color 
{
	return [UIColor colorWithRed:0.666667 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray44_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_LemonChiffon2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_wheat1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_BlanchedAlmond_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_LightBlue2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.133333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_LightGoldenrodYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_linen_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray16_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.600000 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_tan_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.133333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_MediumTurquoise_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.533333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_MediumPurple1_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray97_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.466667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_CornflowerBlue_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.266667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_firebrick4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray20_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.200000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_LightBlue_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.866667 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_IndianRed4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_azure3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.066667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_SlateGray_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_SteelBlue1_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.200000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray69_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_khaki_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_RoyalBlue3_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.666667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_DarkOliveGreen_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.333333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_OliveDrab1_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_MediumVioletRed_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.466667 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_LightSeaGreen_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray73_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.666667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_khaki4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LightSalmon2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_purple_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.000000 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_LimeGreen_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.133333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray45_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.200000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_wheat2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_LightBlue1_Color 
{
	return [UIColor colorWithRed:0.733333 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_LightCyan4_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.666667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LemonChiffon4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray17_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.733333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_MistyRose4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_thistle3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray98_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_firebrick3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_yellow2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_DodgerBlue2_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.800000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_IndianRed3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_gray21_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.400000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_burlywood_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.933333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_DarkOrchid1_Color 
{
	return [UIColor colorWithRed:0.733333 green:1.000000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_azure4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.200000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_tomato2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_MediumPurple3_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.600000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_LawnGreen_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.800000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_coral1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_green1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_RoyalBlue2_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.200000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_orchid_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.666667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_DeepSkyBlue2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray74_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_turquoise_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_maroon4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_LightGoldenrod2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_gray46_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.333333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_wheat3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_LightCyan3_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.266667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray50_Color 
{
	return [UIColor colorWithRed:0.466667 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_DarkOrange4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_DarkOliveGreen4_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.933333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_MistyRose3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray18_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.933333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_chocolate3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray99_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_firebrick2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_IndianRed2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray22_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.533333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_LightSlateGray_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.466667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_RoyalBlue1_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.533333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_orchid1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_coral2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_green2_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_cornsilk3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_SkyBlue1_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray75_Color 
{
	return [UIColor colorWithRed:0.733333 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_NavajoWhite2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_MediumOrchid1_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_HotPink3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_WhiteSmoke_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_YellowGreen_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.666667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray47_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.533333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_AntiqueWhite1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_LightCyan2_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.066667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_wheat4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_LightYellow2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_magenta4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray51_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.133333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_MistyRose2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_gray19_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.000000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_firebrick1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_chocolate2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_IndianRed1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_DodgerBlue1_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.933333 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_yellow3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray23_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.733333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_OliveDrab_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_tomato3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_SlateBlue_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.666667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_tan1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_cornsilk1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_coral3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_green3_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_SaddleBrown_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_MediumBlue_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_gray76_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.133333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_tan2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_MediumSeaGreen_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.800000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_SeaGreen3_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.200000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray80_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.800000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_FloralWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LightCyan1_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray48_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.666667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_tan3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_DarkOrange3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_MediumOrchid3_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.266667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_SpringGreen4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_MistyRose1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray52_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.333333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_PowderBlue_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_SkyBlue_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_chocolate1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_gainsboro_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.800000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_AntiqueWhite3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_HotPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_tan4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_LavenderBlush1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LightGoldenrod3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_bisque1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_honeydew3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.066667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_LightSkyBlue1_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray24_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.866667 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_DarkKhaki_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_orchid2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_LightSlateBlue_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.266667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_coral4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_green4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LightSalmon1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_lavender_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.400000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray77_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.266667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_LightSteelBlue1_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.666667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_SeaGreen1_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.266667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_chartreuse4_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.333333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.933333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray81_Color 
{
	return [UIColor colorWithRed:0.800000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_DarkSeaGreen_Color 
{
	return [UIColor colorWithRed:0.533333 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_DeepPink4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_plum1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray49_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.866667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_violet_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray53_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_burlywood4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_AntiqueWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_thistle4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_honeydew1_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_DarkGoldenrod1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_yellow4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray25_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_DarkOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_plum2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_tomato4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_RoyalBlue_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.066667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_DeepSkyBlue1_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_LavenderBlush2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_LightSkyBlue3_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_orange1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_DarkSeaGreen1_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.066667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_gray78_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_DeepPink2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_gray82_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.066667 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_plum3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_DarkOrange2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_sienna_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.000000 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML_DarkSalmon_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.600000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_MediumPurple_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.200000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_gray54_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.666667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_burlywood3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_magenta_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML_seashell4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_wheat_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_bisque2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_MediumAquamarine_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray26_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.133333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_plum4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_orchid3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_DarkGoldenrod2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_coral_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML_DarkGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_gray30_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.866667 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_brown_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.333333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML_NavajoWhite1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_SkyBlue2_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.933333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_chartreuse3_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_gray79_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.600000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_aquamarine4_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.333333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LightGoldenrod4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_LavenderBlush3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_HotPink4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML_CadetBlue_Color 
{
	return [UIColor colorWithRed:0.333333 green:1.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_gray83_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.266667 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_DarkSlateGray1_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.466667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_LightYellow1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_DarkSeaGreen3_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.733333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_burlywood2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML_pink1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML_gray55_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.800000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_light_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_LightSteelBlue2_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.800000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_MidnightBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.600000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML_goldenrod4_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML_seashell2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_gray27_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.333333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_PapayaWhip_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML_DarkGoldenrod_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.533333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_gray31_Color 
{
	return [UIColor colorWithRed:0.266667 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_turquoise4_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML_orange2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML_gold1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML_pink2_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML_brown1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML_LemonChiffon1_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML_DarkGoldenrod3_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.600000 alpha:1.0];
};

@end