//
// UIColor+Crayon.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
// Created by Mihaela Mihaljević Jakić
// Color codes source: http://www.colourlovers.com/web/blog/2008/04/22/all-120-crayon-names-color-codes-and-fun-facts (spaces between color names removed by hand)
//
//

#import "UIColor+Crayon.h"

@implementation UIColor (Crayon)

+(UIColor *)crayon_Dandelion_Color 
{
	return [UIColor colorWithRed:253/255.0 green:219/255.0 blue:109/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_MangoTango_Color 
{
	return [UIColor colorWithRed:255/255.0 green:130/255.0 blue:67/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RobinEggBlue_Color 
{
	return [UIColor colorWithRed:31/255.0 green:206/255.0 blue:203/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PineGreen_Color 
{
	return [UIColor colorWithRed:21/255.0 green:128/255.0 blue:120/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_WildStrawberry_Color 
{
	return [UIColor colorWithRed:255/255.0 green:67/255.0 blue:164/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Cornflower_Color 
{
	return [UIColor colorWithRed:154/255.0 green:206/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_AtomicTangerine_Color 
{
	return [UIColor colorWithRed:255/255.0 green:164/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_CottonCandy_Color 
{
	return [UIColor colorWithRed:255/255.0 green:188/255.0 blue:217/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Sunglow_Color 
{
	return [UIColor colorWithRed:255/255.0 green:207/255.0 blue:72/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BlueViolet_Color 
{
	return [UIColor colorWithRed:115/255.0 green:102/255.0 blue:189/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Manatee_Color 
{
	return [UIColor colorWithRed:151/255.0 green:154/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_WildWatermelon_Color 
{
	return [UIColor colorWithRed:252/255.0 green:108/255.0 blue:133/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PurplePizzazz_Color 
{
	return [UIColor colorWithRed:255/255.0 green:29/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Cerulean_Color 
{
	return [UIColor colorWithRed:29/255.0 green:172/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_SpringGreen_Color 
{
	return [UIColor colorWithRed:236/255.0 green:234/255.0 blue:190/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BurntOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:127/255.0 blue:73/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Orchid_Color 
{
	return [UIColor colorWithRed:230/255.0 green:168/255.0 blue:215/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Aquamarine_Color 
{
	return [UIColor colorWithRed:120/255.0 green:219/255.0 blue:226/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Magenta_Color 
{
	return [UIColor colorWithRed:246/255.0 green:100/255.0 blue:175/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_LaserLemon_Color 
{
	return [UIColor colorWithRed:253/255.0 green:252/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_GrannySmithApple_Color 
{
	return [UIColor colorWithRed:168/255.0 green:228/255.0 blue:160/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_SeaGreen_Color 
{
	return [UIColor colorWithRed:159/255.0 green:226/255.0 blue:191/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_UnmellowYellow_Color 
{
	return [UIColor colorWithRed:253/255.0 green:252/255.0 blue:116/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RawSienna_Color 
{
	return [UIColor colorWithRed:214/255.0 green:138/255.0 blue:89/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PiggyPink_Color 
{
	return [UIColor colorWithRed:253/255.0 green:215/255.0 blue:228/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_YellowOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:182/255.0 blue:83/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PurpleMountainsMajesty_Color 
{
	return [UIColor colorWithRed:157/255.0 green:129/255.0 blue:186/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Mauvelous_Color 
{
	return [UIColor colorWithRed:239/255.0 green:152/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_MidnightBlue_Color 
{
	return [UIColor colorWithRed:26/255.0 green:72/255.0 blue:118/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_VividTangerine_Color 
{
	return [UIColor colorWithRed:255/255.0 green:160/255.0 blue:137/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Razzmatazz_Color 
{
	return [UIColor colorWithRed:227/255.0 green:37/255.0 blue:107/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Shadow_Color 
{
	return [UIColor colorWithRed:138/255.0 green:121/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PinkSherbet_Color 
{
	return [UIColor colorWithRed:247/255.0 green:128/255.0 blue:161/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Gold_Color 
{
	return [UIColor colorWithRed:231/255.0 green:198/255.0 blue:151/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Blush_Color 
{
	return [UIColor colorWithRed:222/255.0 green:93/255.0 blue:131/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RazzleDazzleRose_Color 
{
	return [UIColor colorWithRed:255/255.0 green:72/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Indigo_Color 
{
	return [UIColor colorWithRed:93/255.0 green:118/255.0 blue:203/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_ForestGreen_Color 
{
	return [UIColor colorWithRed:109/255.0 green:174/255.0 blue:129/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Orange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:117/255.0 blue:56/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Red_Color 
{
	return [UIColor colorWithRed:238/255.0 green:32/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Silver_Color 
{
	return [UIColor colorWithRed:205/255.0 green:197/255.0 blue:194/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_CarnationPink_Color 
{
	return [UIColor colorWithRed:255/255.0 green:170/255.0 blue:204/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Fern_Color 
{
	return [UIColor colorWithRed:113/255.0 green:188/255.0 blue:120/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RoyalPurple_Color 
{
	return [UIColor colorWithRed:120/255.0 green:81/255.0 blue:169/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RedOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:83/255.0 blue:73/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Plum_Color 
{
	return [UIColor colorWithRed:142/255.0 green:69/255.0 blue:133/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Mahogany_Color 
{
	return [UIColor colorWithRed:205/255.0 green:74/255.0 blue:74/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Tan_Color 
{
	return [UIColor colorWithRed:250/255.0 green:167/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_FuzzyWuzzy_Color 
{
	return [UIColor colorWithRed:187/255.0 green:187/255.0 blue:187/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Beaver_Color 
{
	return [UIColor colorWithRed:159/255.0 green:129/255.0 blue:112/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BananaMania_Color 
{
	return [UIColor colorWithRed:250/255.0 green:231/255.0 blue:181/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_WildBlueYonder_Color 
{
	return [UIColor colorWithRed:162/255.0 green:173/255.0 blue:208/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_NeonCarrot_Color 
{
	return [UIColor colorWithRed:255/255.0 green:163/255.0 blue:67/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Shamrock_Color 
{
	return [UIColor colorWithRed:69/255.0 green:206/255.0 blue:162/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_JungleGreen_Color 
{
	return [UIColor colorWithRed:59/255.0 green:176/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Canary_Color 
{
	return [UIColor colorWithRed:255/255.0 green:255/255.0 blue:153/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_HotMagenta_Color 
{
	return [UIColor colorWithRed:255/255.0 green:29/255.0 blue:206/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Melon_Color 
{
	return [UIColor colorWithRed:253/255.0 green:188/255.0 blue:180/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_White_Color 
{
	return [UIColor colorWithRed:237/255.0 green:237/255.0 blue:237/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Tumbleweed_Color 
{
	return [UIColor colorWithRed:222/255.0 green:170/255.0 blue:136/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Timberwolf_Color 
{
	return [UIColor colorWithRed:219/255.0 green:215/255.0 blue:210/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_TickleMePink_Color 
{
	return [UIColor colorWithRed:252/255.0 green:137/255.0 blue:172/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_SkyBlue_Color 
{
	return [UIColor colorWithRed:128/255.0 green:218/255.0 blue:235/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Scarlet_Color 
{
	return [UIColor colorWithRed:252/255.0 green:40/255.0 blue:71/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Almond_Color 
{
	return [UIColor colorWithRed:239/255.0 green:219/255.0 blue:197/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Fuchsia_Color 
{
	return [UIColor colorWithRed:195/255.0 green:100/255.0 blue:197/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_OutrageousOrange_Color 
{
	return [UIColor colorWithRed:255/255.0 green:110/255.0 blue:74/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PacificBlue_Color 
{
	return [UIColor colorWithRed:28/255.0 green:169/255.0 blue:201/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Copper_Color 
{
	return [UIColor colorWithRed:221/255.0 green:148/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Blue_Color 
{
	return [UIColor colorWithRed:31/255.0 green:117/255.0 blue:254/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Gray_Color 
{
	return [UIColor colorWithRed:149/255.0 green:145/255.0 blue:140/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Bittersweet_Color 
{
	return [UIColor colorWithRed:253/255.0 green:124/255.0 blue:110/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RadicalRed_Color 
{
	return [UIColor colorWithRed:255/255.0 green:73/255.0 blue:108/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PurpleHeart_Color 
{
	return [UIColor colorWithRed:116/255.0 green:66/255.0 blue:200/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_PinkFlamingo_Color 
{
	return [UIColor colorWithRed:252/255.0 green:116/255.0 blue:253/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Denim_Color 
{
	return [UIColor colorWithRed:43/255.0 green:108/255.0 blue:196/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Chestnut_Color 
{
	return [UIColor colorWithRed:188/255.0 green:93/255.0 blue:88/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Goldenrod_Color 
{
	return [UIColor colorWithRed:252/255.0 green:217/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_TropicalRainForest_Color 
{
	return [UIColor colorWithRed:23/255.0 green:128/255.0 blue:109/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Yellow_Color 
{
	return [UIColor colorWithRed:252/255.0 green:232/255.0 blue:131/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_CaribbeanGreen_Color 
{
	return [UIColor colorWithRed:28/255.0 green:211/255.0 blue:162/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BrickRed_Color 
{
	return [UIColor colorWithRed:203/255.0 green:65/255.0 blue:84/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_ScreaminGreen_Color 
{
	return [UIColor colorWithRed:118/255.0 green:255/255.0 blue:122/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Asparagus_Color 
{
	return [UIColor colorWithRed:135/255.0 green:169/255.0 blue:107/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BlueBell_Color 
{
	return [UIColor colorWithRed:173/255.0 green:173/255.0 blue:214/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_VioletRed_Color 
{
	return [UIColor colorWithRed:247/255.0 green:83/255.0 blue:148/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_JazzberryJam_Color 
{
	return [UIColor colorWithRed:202/255.0 green:55/255.0 blue:103/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_MacaroniAndCheese_Color 
{
	return [UIColor colorWithRed:255/255.0 green:189/255.0 blue:136/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Apricot_Color 
{
	return [UIColor colorWithRed:253/255.0 green:217/255.0 blue:181/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_SunsetOrange_Color 
{
	return [UIColor colorWithRed:253/255.0 green:94/255.0 blue:83/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_YellowGreen_Color 
{
	return [UIColor colorWithRed:197/255.0 green:227/255.0 blue:132/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Lavender_Color 
{
	return [UIColor colorWithRed:252/255.0 green:180/255.0 blue:213/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BlueGreen_Color 
{
	return [UIColor colorWithRed:25/255.0 green:158/255.0 blue:189/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_BurntSienna_Color 
{
	return [UIColor colorWithRed:234/255.0 green:126/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_NavyBlue_Color 
{
	return [UIColor colorWithRed:25/255.0 green:116/255.0 blue:210/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Brown_Color 
{
	return [UIColor colorWithRed:180/255.0 green:103/255.0 blue:77/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_VioletPurple_Color 
{
	return [UIColor colorWithRed:146/255.0 green:110/255.0 blue:174/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_OuterSpace_Color 
{
	return [UIColor colorWithRed:65/255.0 green:74/255.0 blue:76/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_ShockingPink_Color 
{
	return [UIColor colorWithRed:251/255.0 green:126/255.0 blue:253/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_MountainMeadow_Color 
{
	return [UIColor colorWithRed:48/255.0 green:186/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Salmon_Color 
{
	return [UIColor colorWithRed:255/255.0 green:155/255.0 blue:170/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_AntiqueBrass_Color 
{
	return [UIColor colorWithRed:205/255.0 green:149/255.0 blue:117/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Cerise_Color 
{
	return [UIColor colorWithRed:221/255.0 green:68/255.0 blue:146/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Maroon_Color 
{
	return [UIColor colorWithRed:200/255.0 green:56/255.0 blue:90/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_DesertSand_Color 
{
	return [UIColor colorWithRed:239/255.0 green:205/255.0 blue:184/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_InchWorm_Color 
{
	return [UIColor colorWithRed:178/255.0 green:236/255.0 blue:93/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Green_Color 
{
	return [UIColor colorWithRed:28/255.0 green:172/255.0 blue:120/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Sepia_Color 
{
	return [UIColor colorWithRed:165/255.0 green:105/255.0 blue:79/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Periwinkle_Color 
{
	return [UIColor colorWithRed:197/255.0 green:208/255.0 blue:230/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_TurquoiseBlue_Color 
{
	return [UIColor colorWithRed:119/255.0 green:221/255.0 blue:231/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Peach_Color 
{
	return [UIColor colorWithRed:255/255.0 green:207/255.0 blue:171/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_RedViolet_Color 
{
	return [UIColor colorWithRed:192/255.0 green:68/255.0 blue:143/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_ElectricLime_Color 
{
	return [UIColor colorWithRed:29/255.0 green:249/255.0 blue:20/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Eggplant_Color 
{
	return [UIColor colorWithRed:110/255.0 green:81/255.0 blue:96/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_Wisteria_Color 
{
	return [UIColor colorWithRed:205/255.0 green:164/255.0 blue:222/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_VividViolet_Color 
{
	return [UIColor colorWithRed:143/255.0 green:80/255.0 blue:157/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_CadetBlue_Color 
{
	return [UIColor colorWithRed:176/255.0 green:183/255.0 blue:198/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_GreenYellow_Color 
{
	return [UIColor colorWithRed:240/255.0 green:232/255.0 blue:145/255.0 alpha:255/255.0];
};

+(UIColor *)crayon_OliveGreen_Color 
{
	return [UIColor colorWithRed:186/255.0 green:184/255.0 blue:108/255.0 alpha:255/255.0];
};

@end