//
// UIColor+CopicColors.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
//
//

#import "UIColor+CopicColors.h"

@implementation UIColor (CopicColors)

+(UIColor *)CopicColors_g82_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.854902 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_yr31_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.870588 blue:0.658824 alpha:1.0];
};

+(UIColor *)CopicColors_r11_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.882353 blue:0.835294 alpha:1.0];
};

+(UIColor *)CopicColors_bv34_Color 
{
	return [UIColor colorWithRed:0.623529 green:0.654902 blue:0.737255 alpha:1.0];
};

+(UIColor *)CopicColors_rv000_Color 
{
	return [UIColor colorWithRed:0.956863 green:0.886275 blue:0.933333 alpha:1.0];
};

+(UIColor *)CopicColors_b41_Color 
{
	return [UIColor colorWithRed:0.886275 green:0.941176 blue:0.984314 alpha:1.0];
};

+(UIColor *)CopicColors_bv0000_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.905882 blue:0.949020 alpha:1.0];
};

+(UIColor *)CopicColors_r12_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.827451 blue:0.756863 alpha:1.0];
};

+(UIColor *)CopicColors_v28_Color 
{
	return [UIColor colorWithRed:0.419608 green:0.400000 blue:0.556863 alpha:1.0];
};

+(UIColor *)CopicColors_r43_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.517647 blue:0.556863 alpha:1.0];
};

+(UIColor *)CopicColors_b12_Color 
{
	return [UIColor colorWithRed:0.784314 green:0.901961 blue:0.941176 alpha:1.0];
};

+(UIColor *)CopicColors_g24_Color 
{
	return [UIColor colorWithRed:0.764706 green:0.878431 blue:0.705882 alpha:1.0];
};

+(UIColor *)CopicColors_rv95_Color 
{
	return [UIColor colorWithRed:0.713726 green:0.517647 blue:0.631373 alpha:1.0];
};

+(UIColor *)CopicColors_g85_Color 
{
	return [UIColor colorWithRed:0.615686 green:0.764706 blue:0.666667 alpha:1.0];
};

+(UIColor *)CopicColors_r14_Color 
{
	return [UIColor colorWithRed:0.960784 green:0.607843 blue:0.572549 alpha:1.0];
};

+(UIColor *)CopicColors_yr20_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.882353 blue:0.749020 alpha:1.0];
};

+(UIColor *)CopicColors_b14_Color 
{
	return [UIColor colorWithRed:0.443137 green:0.811765 blue:0.921569 alpha:1.0];
};

+(UIColor *)CopicColors_bv23_Color 
{
	return [UIColor colorWithRed:0.694118 green:0.752941 blue:0.866667 alpha:1.0];
};

+(UIColor *)CopicColors_bg78_Color 
{
	return [UIColor colorWithRed:0.286275 green:0.439216 blue:0.419608 alpha:1.0];
};

+(UIColor *)CopicColors_c10_Color 
{
	return [UIColor colorWithRed:0.125490 green:0.168627 blue:0.192157 alpha:1.0];
};

+(UIColor *)CopicColors_b45_Color 
{
	return [UIColor colorWithRed:0.458824 green:0.752941 blue:0.917647 alpha:1.0];
};

+(UIColor *)CopicColors_r46_Color 
{
	return [UIColor colorWithRed:0.878431 green:0.301961 blue:0.411765 alpha:1.0];
};

+(UIColor *)CopicColors_r000_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.941176 blue:0.905882 alpha:1.0];
};

+(UIColor *)CopicColors_bg53_Color 
{
	return [UIColor colorWithRed:0.674510 green:0.811765 blue:0.819608 alpha:1.0];
};

+(UIColor *)CopicColors_bv11_Color 
{
	return [UIColor colorWithRed:0.831373 green:0.823529 blue:0.909804 alpha:1.0];
};

+(UIColor *)CopicColors_yg45_Color 
{
	return [UIColor colorWithRed:0.705882 green:0.862745 blue:0.717647 alpha:1.0];
};

+(UIColor *)CopicColors_yr21_Color 
{
	return [UIColor colorWithRed:0.960784 green:0.866667 blue:0.694118 alpha:1.0];
};

+(UIColor *)CopicColors_b16_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.737255 blue:0.917647 alpha:1.0];
};

+(UIColor *)CopicColors_g28_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.580392 blue:0.384314 alpha:1.0];
};

+(UIColor *)CopicColors_r17_Color 
{
	return [UIColor colorWithRed:0.956863 green:0.517647 blue:0.423529 alpha:1.0];
};

+(UIColor *)CopicColors_y21_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.933333 blue:0.760784 alpha:1.0];
};

+(UIColor *)CopicColors_g29_Color 
{
	return [UIColor colorWithRed:0.098039 green:0.486275 blue:0.364706 alpha:1.0];
};

+(UIColor *)CopicColors_bv25_Color 
{
	return [UIColor colorWithRed:0.505882 green:0.517647 blue:0.654902 alpha:1.0];
};

+(UIColor *)CopicColors_t10_Color 
{
	return [UIColor colorWithRed:0.196078 green:0.180392 blue:0.176471 alpha:1.0];
};

+(UIColor *)CopicColors_b18_Color 
{
	return [UIColor colorWithRed:0.113725 green:0.541176 blue:0.796078 alpha:1.0];
};

+(UIColor *)CopicColors_n0_Color 
{
	return [UIColor colorWithRed:0.925490 green:0.933333 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_b79_Color 
{
	return [UIColor colorWithRed:0.231373 green:0.278431 blue:0.615686 alpha:1.0];
};

+(UIColor *)CopicColors_n1_Color 
{
	return [UIColor colorWithRed:0.886275 green:0.890196 blue:0.898039 alpha:1.0];
};

+(UIColor *)CopicColors_yg21_Color 
{
	return [UIColor colorWithRed:0.968627 green:0.964706 blue:0.745098 alpha:1.0];
};

+(UIColor *)CopicColors_bv00_Color 
{
	return [UIColor colorWithRed:0.878431 green:0.862745 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_y23_Color 
{
	return [UIColor colorWithRed:0.984314 green:0.890196 blue:0.701961 alpha:1.0];
};

+(UIColor *)CopicColors_n2_Color 
{
	return [UIColor colorWithRed:0.854902 green:0.858824 blue:0.866667 alpha:1.0];
};

+(UIColor *)CopicColors_bv13_Color 
{
	return [UIColor colorWithRed:0.517647 green:0.568627 blue:0.784314 alpha:1.0];
};

+(UIColor *)CopicColors_yr23_Color 
{
	return [UIColor colorWithRed:0.925490 green:0.811765 blue:0.545098 alpha:1.0];
};

+(UIColor *)CopicColors_n3_Color 
{
	return [UIColor colorWithRed:0.819608 green:0.823529 blue:0.831373 alpha:1.0];
};

+(UIColor *)CopicColors_rv99_Color 
{
	return [UIColor colorWithRed:0.352941 green:0.282353 blue:0.345098 alpha:1.0];
};

+(UIColor *)CopicColors_n4_Color 
{
	return [UIColor colorWithRed:0.737255 green:0.741176 blue:0.756863 alpha:1.0];
};

+(UIColor *)CopicColors_bv01_Color 
{
	return [UIColor colorWithRed:0.768627 green:0.788235 blue:0.901961 alpha:1.0];
};

+(UIColor *)CopicColors_n5_Color 
{
	return [UIColor colorWithRed:0.658824 green:0.662745 blue:0.678431 alpha:1.0];
};

+(UIColor *)CopicColors_yr24_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.811765 blue:0.392157 alpha:1.0];
};

+(UIColor *)CopicColors_n6_Color 
{
	return [UIColor colorWithRed:0.580392 green:0.584314 blue:0.600000 alpha:1.0];
};

+(UIColor *)CopicColors_fyr1_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.800000 blue:0.600000 alpha:1.0];
};

+(UIColor *)CopicColors_n7_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.470588 blue:0.486275 alpha:1.0];
};

+(UIColor *)CopicColors_y26_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.866667 blue:0.403922 alpha:1.0];
};

+(UIColor *)CopicColors_tg13_Color 
{
	return [UIColor colorWithRed:0.831373 green:0.898039 blue:0.623529 alpha:1.0];
};

+(UIColor *)CopicColors_e70_Color 
{
	return [UIColor colorWithRed:0.937255 green:0.917647 blue:0.901961 alpha:1.0];
};

+(UIColor *)CopicColors_n8_Color 
{
	return [UIColor colorWithRed:0.388235 green:0.392157 blue:0.400000 alpha:1.0];
};

+(UIColor *)CopicColors_e40_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.909804 blue:0.862745 alpha:1.0];
};

+(UIColor *)CopicColors_bv02_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.721569 blue:0.858824 alpha:1.0];
};

+(UIColor *)CopicColors_bg57_Color 
{
	return [UIColor colorWithRed:0.392157 green:0.745098 blue:0.745098 alpha:1.0];
};

+(UIColor *)CopicColors_n9_Color 
{
	return [UIColor colorWithRed:0.298039 green:0.301961 blue:0.309804 alpha:1.0];
};

+(UIColor *)CopicColors_fy1_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.964706 blue:0.592157 alpha:1.0];
};

+(UIColor *)CopicColors_yg23_Color 
{
	return [UIColor colorWithRed:0.901961 green:0.921569 blue:0.560784 alpha:1.0];
};

+(UIColor *)CopicColors_yr12_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.886275 blue:0.650980 alpha:1.0];
};

+(UIColor *)CopicColors_e71_Color 
{
	return [UIColor colorWithRed:0.631373 green:0.517647 blue:0.486275 alpha:1.0];
};

+(UIColor *)CopicColors_e41_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.945098 blue:0.882353 alpha:1.0];
};

+(UIColor *)CopicColors_e11_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.913725 blue:0.839216 alpha:1.0];
};

+(UIColor *)CopicColors_y28_Color 
{
	return [UIColor colorWithRed:0.792157 green:0.658824 blue:0.411765 alpha:1.0];
};

+(UIColor *)CopicColors_bg32_Color 
{
	return [UIColor colorWithRed:0.737255 green:0.886275 blue:0.843137 alpha:1.0];
};

+(UIColor *)CopicColors_fv2_Color 
{
	return [UIColor colorWithRed:0.498039 green:0.454902 blue:0.713726 alpha:1.0];
};

+(UIColor *)CopicColors_rv63_Color 
{
	return [UIColor colorWithRed:0.815686 green:0.615686 blue:0.682353 alpha:1.0];
};

+(UIColor *)CopicColors_bg45_Color 
{
	return [UIColor colorWithRed:0.686275 green:0.874510 blue:0.874510 alpha:1.0];
};

+(UIColor *)CopicColors_yg11_Color 
{
	return [UIColor colorWithRed:0.898039 green:0.941176 blue:0.815686 alpha:1.0];
};

+(UIColor *)CopicColors_e42_Color 
{
	return [UIColor colorWithRed:0.952941 green:0.917647 blue:0.850980 alpha:1.0];
};

+(UIColor *)CopicColors_yr00_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.839216 blue:0.741176 alpha:1.0];
};

+(UIColor *)CopicColors_bv29_Color 
{
	return [UIColor colorWithRed:0.219608 green:0.270588 blue:0.345098 alpha:1.0];
};

+(UIColor *)CopicColors_e43_Color 
{
	return [UIColor colorWithRed:0.909804 green:0.854902 blue:0.741176 alpha:1.0];
};

+(UIColor *)CopicColors_e13_Color 
{
	return [UIColor colorWithRed:0.913725 green:0.772549 blue:0.686275 alpha:1.0];
};

+(UIColor *)CopicColors_yr01_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.854902 blue:0.760784 alpha:1.0];
};

+(UIColor *)CopicColors_yg25_Color 
{
	return [UIColor colorWithRed:0.815686 green:0.882353 blue:0.482353 alpha:1.0];
};

+(UIColor *)CopicColors_yr14_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.784314 blue:0.305882 alpha:1.0];
};

+(UIColor *)CopicColors_bv04_Color 
{
	return [UIColor colorWithRed:0.486275 green:0.592157 blue:0.807843 alpha:1.0];
};

+(UIColor *)CopicColors_e74_Color 
{
	return [UIColor colorWithRed:0.631373 green:0.517647 blue:0.486275 alpha:1.0];
};

+(UIColor *)CopicColors_e44_Color 
{
	return [UIColor colorWithRed:0.541176 green:0.431373 blue:0.349020 alpha:1.0];
};

+(UIColor *)CopicColors_bv17_Color 
{
	return [UIColor colorWithRed:0.431373 green:0.517647 blue:0.741176 alpha:1.0];
};

+(UIColor *)CopicColors_e0000_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.980392 blue:0.956863 alpha:1.0];
};

+(UIColor *)CopicColors_bg000_Color 
{
	return [UIColor colorWithRed:0.898039 green:0.956863 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_yg00_Color 
{
	return [UIColor colorWithRed:0.901961 green:0.901961 blue:0.619608 alpha:1.0];
};

+(UIColor *)CopicColors_rv52_Color 
{
	return [UIColor colorWithRed:0.976471 green:0.792157 blue:0.870588 alpha:1.0];
};

+(UIColor *)CopicColors_e15_Color 
{
	return [UIColor colorWithRed:0.984314 green:0.733333 blue:0.552941 alpha:1.0];
};

+(UIColor *)CopicColors_bg34_Color 
{
	return [UIColor colorWithRed:0.639216 green:0.854902 blue:0.843137 alpha:1.0];
};

+(UIColor *)CopicColors_yr02_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.862745 blue:0.772549 alpha:1.0];
};

+(UIColor *)CopicColors_yr15_Color 
{
	return [UIColor colorWithRed:0.984314 green:0.721569 blue:0.517647 alpha:1.0];
};

+(UIColor *)CopicColors_v12_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.843137 blue:0.913725 alpha:1.0];
};

+(UIColor *)CopicColors_yg01_Color 
{
	return [UIColor colorWithRed:0.886275 green:0.921569 blue:0.698039 alpha:1.0];
};

+(UIColor *)CopicColors_e77_Color 
{
	return [UIColor colorWithRed:0.498039 green:0.376471 blue:0.305882 alpha:1.0];
};

+(UIColor *)CopicColors_e47_Color 
{
	return [UIColor colorWithRed:0.541176 green:0.431373 blue:0.349020 alpha:1.0];
};

+(UIColor *)CopicColors_e17_Color 
{
	return [UIColor colorWithRed:0.721569 green:0.372549 blue:0.341176 alpha:1.0];
};

+(UIColor *)CopicColors_rv66_Color 
{
	return [UIColor colorWithRed:0.721569 green:0.415686 blue:0.517647 alpha:1.0];
};

+(UIColor *)CopicColors_yr16_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.717647 blue:0.160784 alpha:1.0];
};

+(UIColor *)CopicColors_w10_Color 
{
	return [UIColor colorWithRed:0.188235 green:0.184314 blue:0.168627 alpha:1.0];
};

+(UIColor *)CopicColors_e18_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.325490 blue:0.301961 alpha:1.0];
};

+(UIColor *)CopicColors_bg10_Color 
{
	return [UIColor colorWithRed:0.862745 green:0.941176 blue:0.937255 alpha:1.0];
};

+(UIColor *)CopicColors_g40_Color 
{
	return [UIColor colorWithRed:0.894118 green:0.945098 blue:0.874510 alpha:1.0];
};

+(UIColor *)CopicColors_e79_Color 
{
	return [UIColor colorWithRed:0.290196 green:0.172549 blue:0.133333 alpha:1.0];
};

+(UIColor *)CopicColors_100_Color 
{
	return [UIColor colorWithRed:0.192157 green:0.168627 blue:0.168627 alpha:1.0];
};

+(UIColor *)CopicColors_e49_Color 
{
	return [UIColor colorWithRed:0.388235 green:0.298039 blue:0.235294 alpha:1.0];
};

+(UIColor *)CopicColors_bg23_Color 
{
	return [UIColor colorWithRed:0.741176 green:0.898039 blue:0.866667 alpha:1.0];
};

+(UIColor *)CopicColors_e19_Color 
{
	return [UIColor colorWithRed:0.768627 green:0.321569 blue:0.219608 alpha:1.0];
};

+(UIColor *)CopicColors_bg49_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.713726 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_v15_Color 
{
	return [UIColor colorWithRed:0.827451 green:0.650980 blue:0.803922 alpha:1.0];
};

+(UIColor *)CopicColors_yr04_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.764706 blue:0.411765 alpha:1.0];
};

+(UIColor *)CopicColors_r30_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.890196 blue:0.874510 alpha:1.0];
};

+(UIColor *)CopicColors_r00_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.917647 blue:0.882353 alpha:1.0];
};

+(UIColor *)CopicColors_bg11_Color 
{
	return [UIColor colorWithRed:0.807843 green:0.921569 blue:0.945098 alpha:1.0];
};

+(UIColor *)CopicColors_b60_Color 
{
	return [UIColor colorWithRed:0.854902 green:0.882353 blue:0.952941 alpha:1.0];
};

+(UIColor *)CopicColors_rv42_Color 
{
	return [UIColor colorWithRed:0.972549 green:0.733333 blue:0.713726 alpha:1.0];
};

+(UIColor *)CopicColors_rv0000_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.917647 blue:0.960784 alpha:1.0];
};

+(UIColor *)CopicColors_b00_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.941176 blue:0.956863 alpha:1.0];
};

+(UIColor *)CopicColors_rv55_Color 
{
	return [UIColor colorWithRed:0.913725 green:0.647059 blue:0.792157 alpha:1.0];
};

+(UIColor *)CopicColors_g12_Color 
{
	return [UIColor colorWithRed:0.823529 green:0.909804 blue:0.768627 alpha:1.0];
};

+(UIColor *)CopicColors_b91_Color 
{
	return [UIColor colorWithRed:0.835294 green:0.886275 blue:0.921569 alpha:1.0];
};

+(UIColor *)CopicColors_r01_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.878431 blue:0.847059 alpha:1.0];
};

+(UIColor *)CopicColors_bv000_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.905882 blue:0.949020 alpha:1.0];
};

+(UIColor *)CopicColors_bv08_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.905882 blue:0.949020 alpha:1.0];
};

+(UIColor *)CopicColors_t0_Color 
{
	return [UIColor colorWithRed:0.925490 green:0.933333 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_t1_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.917647 blue:0.909804 alpha:1.0];
};

+(UIColor *)CopicColors_g43_Color 
{
	return [UIColor colorWithRed:0.843137 green:0.905882 blue:0.658824 alpha:1.0];
};

+(UIColor *)CopicColors_b01_Color 
{
	return [UIColor colorWithRed:0.839216 green:0.933333 blue:0.949020 alpha:1.0];
};

+(UIColor *)CopicColors_r02_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.827451 blue:0.780392 alpha:1.0];
};

+(UIColor *)CopicColors_r32_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.756863 blue:0.729412 alpha:1.0];
};

+(UIColor *)CopicColors_t2_Color 
{
	return [UIColor colorWithRed:0.878431 green:0.878431 blue:0.870588 alpha:1.0];
};

+(UIColor *)CopicColors_v17_Color 
{
	return [UIColor colorWithRed:0.627451 green:0.572549 blue:0.780392 alpha:1.0];
};

+(UIColor *)CopicColors_t3_Color 
{
	return [UIColor colorWithRed:0.819608 green:0.823529 blue:0.800000 alpha:1.0];
};

+(UIColor *)CopicColors_b32_Color 
{
	return [UIColor colorWithRed:0.886275 green:0.937255 blue:0.968627 alpha:1.0];
};

+(UIColor *)CopicColors_yg03_Color 
{
	return [UIColor colorWithRed:0.870588 green:0.917647 blue:0.666667 alpha:1.0];
};

+(UIColor *)CopicColors_b02_Color 
{
	return [UIColor colorWithRed:0.701961 green:0.890196 blue:0.945098 alpha:1.0];
};

+(UIColor *)CopicColors_yg17_Color 
{
	return [UIColor colorWithRed:0.447059 green:0.756863 blue:0.337255 alpha:1.0];
};

+(UIColor *)CopicColors_g14_Color 
{
	return [UIColor colorWithRed:0.592157 green:0.811765 blue:0.564706 alpha:1.0];
};

+(UIColor *)CopicColors_b93_Color 
{
	return [UIColor colorWithRed:0.584314 green:0.756863 blue:0.854902 alpha:1.0];
};

+(UIColor *)CopicColors_rv69_Color 
{
	return [UIColor colorWithRed:0.545098 green:0.341176 blue:0.431373 alpha:1.0];
};

+(UIColor *)CopicColors_b63_Color 
{
	return [UIColor colorWithRed:0.654902 green:0.733333 blue:0.878431 alpha:1.0];
};

+(UIColor *)CopicColors_t4_Color 
{
	return [UIColor colorWithRed:0.737255 green:0.733333 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_t5_Color 
{
	return [UIColor colorWithRed:0.658824 green:0.654902 blue:0.639216 alpha:1.0];
};

+(UIColor *)CopicColors_yr18_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.419608 blue:0.235294 alpha:1.0];
};

+(UIColor *)CopicColors_bg13_Color 
{
	return [UIColor colorWithRed:0.768627 green:0.905882 blue:0.913725 alpha:1.0];
};

+(UIColor *)CopicColors_t6_Color 
{
	return [UIColor colorWithRed:0.580392 green:0.584314 blue:0.564706 alpha:1.0];
};

+(UIColor *)CopicColors_yg05_Color 
{
	return [UIColor colorWithRed:0.839216 green:0.898039 blue:0.572549 alpha:1.0];
};

+(UIColor *)CopicColors_b34_Color 
{
	return [UIColor colorWithRed:0.509804 green:0.764706 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_t7_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.462745 blue:0.454902 alpha:1.0];
};

+(UIColor *)CopicColors_r35_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.443137 blue:0.521569 alpha:1.0];
};

+(UIColor *)CopicColors_g46_Color 
{
	return [UIColor colorWithRed:0.474510 green:0.054902 blue:0.470588 alpha:1.0];
};

+(UIColor *)CopicColors_g16_Color 
{
	return [UIColor colorWithRed:0.376471 green:0.756863 blue:0.596078 alpha:1.0];
};

+(UIColor *)CopicColors_b95_Color 
{
	return [UIColor colorWithRed:0.376471 green:0.772549 blue:0.811765 alpha:1.0];
};

+(UIColor *)CopicColors_c00_Color 
{
	return [UIColor colorWithRed:0.878431 green:0.905882 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_b04_Color 
{
	return [UIColor colorWithRed:0.450980 green:0.811765 blue:0.901961 alpha:1.0];
};

+(UIColor *)CopicColors_r05_Color 
{
	return [UIColor colorWithRed:0.964706 green:0.568627 blue:0.482353 alpha:1.0];
};

+(UIColor *)CopicColors_t8_Color 
{
	return [UIColor colorWithRed:0.388235 green:0.392157 blue:0.372549 alpha:1.0];
};

+(UIColor *)CopicColors_bg01_Color 
{
	return [UIColor colorWithRed:0.780392 green:0.901961 blue:0.980392 alpha:1.0];
};

+(UIColor *)CopicColors_b05_Color 
{
	return [UIColor colorWithRed:0.250980 green:0.772549 blue:0.901961 alpha:1.0];
};

+(UIColor *)CopicColors_rv32_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.827451 blue:0.807843 alpha:1.0];
};

+(UIColor *)CopicColors_g17_Color 
{
	return [UIColor colorWithRed:0.078431 green:0.701961 blue:0.490196 alpha:1.0];
};

+(UIColor *)CopicColors_t9_Color 
{
	return [UIColor colorWithRed:0.298039 green:0.294118 blue:0.286275 alpha:1.0];
};

+(UIColor *)CopicColors_yg06_Color 
{
	return [UIColor colorWithRed:0.768627 green:0.874510 blue:0.572549 alpha:1.0];
};

+(UIColor *)CopicColors_b66_Color 
{
	return [UIColor colorWithRed:0.407843 green:0.533333 blue:0.772549 alpha:1.0];
};

+(UIColor *)CopicColors_yr07_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.435294 blue:0.223529 alpha:1.0];
};

+(UIColor *)CopicColors_r37_Color 
{
	return [UIColor colorWithRed:0.909804 green:0.423529 blue:0.454902 alpha:1.0];
};

+(UIColor *)CopicColors_b06_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.701961 blue:0.901961 alpha:1.0];
};

+(UIColor *)CopicColors_r07_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.435294 blue:0.223529 alpha:1.0];
};

+(UIColor *)CopicColors_b97_Color 
{
	return [UIColor colorWithRed:0.270588 green:0.478431 blue:0.603922 alpha:1.0];
};

+(UIColor *)CopicColors_b37_Color 
{
	return [UIColor colorWithRed:0.082353 green:0.435294 blue:0.643137 alpha:1.0];
};

+(UIColor *)CopicColors_bg02_Color 
{
	return [UIColor colorWithRed:0.776471 green:0.909804 blue:0.917647 alpha:1.0];
};

+(UIColor *)CopicColors_bg15_Color 
{
	return [UIColor colorWithRed:0.627451 green:0.850980 blue:0.823529 alpha:1.0];
};

+(UIColor *)CopicColors_g19_Color 
{
	return [UIColor colorWithRed:0.176471 green:0.725490 blue:0.541176 alpha:1.0];
};

+(UIColor *)CopicColors_r08_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.403922 blue:0.329412 alpha:1.0];
};

+(UIColor *)CopicColors_0_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)CopicColors_y11_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.984314 blue:0.800000 alpha:1.0];
};

+(UIColor *)CopicColors_w0_Color 
{
	return [UIColor colorWithRed:0.925490 green:0.925490 blue:0.894118 alpha:1.0];
};

+(UIColor *)CopicColors_yg07_Color 
{
	return [UIColor colorWithRed:0.647059 green:0.811765 blue:0.309804 alpha:1.0];
};

+(UIColor *)CopicColors_yr09_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.333333 blue:0.141176 alpha:1.0];
};

+(UIColor *)CopicColors_r39_Color 
{
	return [UIColor colorWithRed:0.796078 green:0.282353 blue:0.478431 alpha:1.0];
};

+(UIColor *)CopicColors_w1_Color 
{
	return [UIColor colorWithRed:0.905882 green:0.905882 blue:0.874510 alpha:1.0];
};

+(UIColor *)CopicColors_b99_Color 
{
	return [UIColor colorWithRed:0.058824 green:0.329412 blue:0.494118 alpha:1.0];
};

+(UIColor *)CopicColors_b69_Color 
{
	return [UIColor colorWithRed:0.129412 green:0.396078 blue:0.682353 alpha:1.0];
};

+(UIColor *)CopicColors_rv21_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.909804 blue:0.905882 alpha:1.0];
};

+(UIColor *)CopicColors_b39_Color 
{
	return [UIColor colorWithRed:0.168627 green:0.392157 blue:0.662745 alpha:1.0];
};

+(UIColor *)CopicColors_rv34_Color 
{
	return [UIColor colorWithRed:0.976471 green:0.686275 blue:0.682353 alpha:1.0];
};

+(UIColor *)CopicColors_w2_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.866667 blue:0.835294 alpha:1.0];
};

+(UIColor *)CopicColors_bg0000_Color 
{
	return [UIColor colorWithRed:0.937255 green:0.972549 blue:0.952941 alpha:1.0];
};

+(UIColor *)CopicColors_y13_Color 
{
	return [UIColor colorWithRed:0.984314 green:0.968627 blue:0.682353 alpha:1.0];
};

+(UIColor *)CopicColors_w3_Color 
{
	return [UIColor colorWithRed:0.823529 green:0.823529 blue:0.792157 alpha:1.0];
};

+(UIColor *)CopicColors_w4_Color 
{
	return [UIColor colorWithRed:0.737255 green:0.741176 blue:0.717647 alpha:1.0];
};

+(UIColor *)CopicColors_w5_Color 
{
	return [UIColor colorWithRed:0.658824 green:0.662745 blue:0.643137 alpha:1.0];
};

+(UIColor *)CopicColors_v000_Color 
{
	return [UIColor colorWithRed:0.913725 green:0.898039 blue:0.952941 alpha:1.0];
};

+(UIColor *)CopicColors_w6_Color 
{
	return [UIColor colorWithRed:0.580392 green:0.584314 blue:0.560784 alpha:1.0];
};

+(UIColor *)CopicColors_y15_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.913725 blue:0.423529 alpha:1.0];
};

+(UIColor *)CopicColors_yg09_Color 
{
	return [UIColor colorWithRed:0.509804 green:0.772549 blue:0.400000 alpha:1.0];
};

+(UIColor *)CopicColors_y000_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.988235 blue:0.913725 alpha:1.0];
};

+(UIColor *)CopicColors_v0000_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.929412 blue:0.964706 alpha:1.0];
};

+(UIColor *)CopicColors_w7_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.470588 blue:0.450980 alpha:1.0];
};

+(UIColor *)CopicColors_rv10_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.925490 blue:0.956863 alpha:1.0];
};

+(UIColor *)CopicColors_w8_Color 
{
	return [UIColor colorWithRed:0.388235 green:0.392157 blue:0.372549 alpha:1.0];
};

+(UIColor *)CopicColors_rv23_Color 
{
	return [UIColor colorWithRed:0.972549 green:0.729412 blue:0.788235 alpha:1.0];
};

+(UIColor *)CopicColors_bg05_Color 
{
	return [UIColor colorWithRed:0.113725 green:0.721569 blue:0.807843 alpha:1.0];
};

+(UIColor *)CopicColors_w9_Color 
{
	return [UIColor colorWithRed:0.298039 green:0.301961 blue:0.282353 alpha:1.0];
};

+(UIColor *)CopicColors_e30_Color 
{
	return [UIColor colorWithRed:0.968627 green:0.941176 blue:0.839216 alpha:1.0];
};

+(UIColor *)CopicColors_bg18_Color 
{
	return [UIColor colorWithRed:0.215686 green:0.752941 blue:0.690196 alpha:1.0];
};

+(UIColor *)CopicColors_e00_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.952941 blue:0.917647 alpha:1.0];
};

+(UIColor *)CopicColors_y17_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.894118 blue:0.333333 alpha:1.0];
};

+(UIColor *)CopicColors_e31_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.901961 blue:0.807843 alpha:1.0];
};

+(UIColor *)CopicColors_rv11_Color 
{
	return [UIColor colorWithRed:0.984314 green:0.839216 blue:0.866667 alpha:1.0];
};

+(UIColor *)CopicColors_e01_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.933333 blue:0.894118 alpha:1.0];
};

+(UIColor *)CopicColors_y18_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.929412 blue:0.333333 alpha:1.0];
};

+(UIColor *)CopicColors_e02_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.925490 blue:0.878431 alpha:1.0];
};

+(UIColor *)CopicColors_y19_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.913725 blue:0.243137 alpha:1.0];
};

+(UIColor *)CopicColors_e93_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.823529 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_e33_Color 
{
	return [UIColor colorWithRed:0.952941 green:0.823529 blue:0.694118 alpha:1.0];
};

+(UIColor *)CopicColors_rv25_Color 
{
	return [UIColor colorWithRed:0.956863 green:0.576471 blue:0.745098 alpha:1.0];
};

+(UIColor *)CopicColors_bg07_Color 
{
	return [UIColor colorWithRed:0.113725 green:0.721569 blue:0.807843 alpha:1.0];
};

+(UIColor *)CopicColors_e34_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.792157 blue:0.650980 alpha:1.0];
};

+(UIColor *)CopicColors_v91_Color 
{
	return [UIColor colorWithRed:0.909804 green:0.768627 blue:0.815686 alpha:1.0];
};

+(UIColor *)CopicColors_e04_Color 
{
	return [UIColor colorWithRed:0.894118 green:0.737255 blue:0.768627 alpha:1.0];
};

+(UIColor *)CopicColors_e95_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.737255 blue:0.494118 alpha:1.0];
};

+(UIColor *)CopicColors_rv00_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.854902 blue:0.917647 alpha:1.0];
};

+(UIColor *)CopicColors_v01_Color 
{
	return [UIColor colorWithRed:0.894118 green:0.756863 blue:0.850980 alpha:1.0];
};

+(UIColor *)CopicColors_rv13_Color 
{
	return [UIColor colorWithRed:0.976471 green:0.788235 blue:0.843137 alpha:1.0];
};

+(UIColor *)CopicColors_e35_Color 
{
	return [UIColor colorWithRed:0.901961 green:0.764706 blue:0.639216 alpha:1.0];
};

+(UIColor *)CopicColors_yg91_Color 
{
	return [UIColor colorWithRed:0.854902 green:0.843137 blue:0.682353 alpha:1.0];
};

+(UIColor *)CopicColors_v93_Color 
{
	return [UIColor colorWithRed:0.898039 green:0.756863 blue:0.858824 alpha:1.0];
};

+(UIColor *)CopicColors_g0000_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.968627 blue:0.952941 alpha:1.0];
};

+(UIColor *)CopicColors_e97_Color 
{
	return [UIColor colorWithRed:0.705882 green:0.376471 blue:0.203922 alpha:1.0];
};

+(UIColor *)CopicColors_rv14_Color 
{
	return [UIColor colorWithRed:0.956863 green:0.584314 blue:0.717647 alpha:1.0];
};

+(UIColor *)CopicColors_e37_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.568627 blue:0.349020 alpha:1.0];
};

+(UIColor *)CopicColors_e07_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.505882 blue:0.415686 alpha:1.0];
};

+(UIColor *)CopicColors_bg09_Color 
{
	return [UIColor colorWithRed:0.862745 green:0.941176 blue:0.937255 alpha:1.0];
};

+(UIColor *)CopicColors_b000_Color 
{
	return [UIColor colorWithRed:0.901961 green:0.956863 blue:0.960784 alpha:1.0];
};

+(UIColor *)CopicColors_v04_Color 
{
	return [UIColor colorWithRed:0.901961 green:0.666667 blue:0.807843 alpha:1.0];
};

+(UIColor *)CopicColors_v95_Color 
{
	return [UIColor colorWithRed:0.717647 green:0.486275 blue:0.658824 alpha:1.0];
};

+(UIColor *)CopicColors_e08_Color 
{
	return [UIColor colorWithRed:0.792157 green:0.396078 blue:0.325490 alpha:1.0];
};

+(UIColor *)CopicColors_rv02_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.835294 blue:0.901961 alpha:1.0];
};

+(UIColor *)CopicColors_e000_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.960784 blue:0.933333 alpha:1.0];
};

+(UIColor *)CopicColors_e99_Color 
{
	return [UIColor colorWithRed:0.705882 green:0.376471 blue:0.203922 alpha:1.0];
};

+(UIColor *)CopicColors_w00_Color 
{
	return [UIColor colorWithRed:0.952941 green:0.952941 blue:0.921569 alpha:1.0];
};

+(UIColor *)CopicColors_v05_Color 
{
	return [UIColor colorWithRed:0.886275 green:0.650980 blue:0.792157 alpha:1.0];
};

+(UIColor *)CopicColors_g00_Color 
{
	return [UIColor colorWithRed:0.890196 green:0.949020 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_e39_Color 
{
	return [UIColor colorWithRed:0.772549 green:0.454902 blue:0.247059 alpha:1.0];
};

+(UIColor *)CopicColors_yg93_Color 
{
	return [UIColor colorWithRed:0.823529 green:0.823529 blue:0.611765 alpha:1.0];
};

+(UIColor *)CopicColors_e09_Color 
{
	return [UIColor colorWithRed:0.850980 green:0.415686 blue:0.309804 alpha:1.0];
};

+(UIColor *)CopicColors_yr82_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.776471 blue:0.552941 alpha:1.0];
};

+(UIColor *)CopicColors_yg0000_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.968627 blue:0.878431 alpha:1.0];
};

+(UIColor *)CopicColors_r20_Color 
{
	return [UIColor colorWithRed:0.988235 green:0.843137 blue:0.811765 alpha:1.0];
};

+(UIColor *)CopicColors_v06_Color 
{
	return [UIColor colorWithRed:0.807843 green:0.584314 blue:0.760784 alpha:1.0];
};

+(UIColor *)CopicColors_r81_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.784314 blue:0.839216 alpha:1.0];
};

+(UIColor *)CopicColors_r21_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.756863 blue:0.713726 alpha:1.0];
};

+(UIColor *)CopicColors_g02_Color 
{
	return [UIColor colorWithRed:0.811765 green:0.909804 blue:0.827451 alpha:1.0];
};

+(UIColor *)CopicColors_rv29_Color 
{
	return [UIColor colorWithRed:0.937255 green:0.282353 blue:0.501961 alpha:1.0];
};

+(UIColor *)CopicColors_b21_Color 
{
	return [UIColor colorWithRed:0.858824 green:0.929412 blue:0.976471 alpha:1.0];
};

+(UIColor *)CopicColors_tr000_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.925490 blue:0.847059 alpha:1.0];
};

+(UIColor *)CopicColors_r22_Color 
{
	return [UIColor colorWithRed:0.972549 green:0.717647 blue:0.694118 alpha:1.0];
};

+(UIColor *)CopicColors_g03_Color 
{
	return [UIColor colorWithRed:0.713726 green:0.854902 blue:0.611765 alpha:1.0];
};

+(UIColor *)CopicColors_rv04_Color 
{
	return [UIColor colorWithRed:0.964706 green:0.639216 blue:0.749020 alpha:1.0];
};

+(UIColor *)CopicColors_r83_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.611765 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_bg90_Color 
{
	return [UIColor colorWithRed:0.729412 green:0.756863 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_rv17_Color 
{
	return [UIColor colorWithRed:0.858824 green:0.494118 blue:0.701961 alpha:1.0];
};

+(UIColor *)CopicColors_g94_Color 
{
	return [UIColor colorWithRed:0.596078 green:0.654902 blue:0.525490 alpha:1.0];
};

+(UIColor *)CopicColors_b52_Color 
{
	return [UIColor colorWithRed:0.678431 green:0.803922 blue:0.862745 alpha:1.0];
};

+(UIColor *)CopicColors_v09_Color 
{
	return [UIColor colorWithRed:0.529412 green:0.329412 blue:0.631373 alpha:1.0];
};

+(UIColor *)CopicColors_v99_Color 
{
	return [UIColor colorWithRed:0.321569 green:0.262745 blue:0.345098 alpha:1.0];
};

+(UIColor *)CopicColors_g000_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.960784 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_yg95_Color 
{
	return [UIColor colorWithRed:0.796078 green:0.776471 blue:0.368627 alpha:1.0];
};

+(UIColor *)CopicColors_b23_Color 
{
	return [UIColor colorWithRed:0.572549 green:0.760784 blue:0.909804 alpha:1.0];
};

+(UIColor *)CopicColors_frv1_Color 
{
	return [UIColor colorWithRed:0.960784 green:0.639216 blue:0.780392 alpha:1.0];
};

+(UIColor *)CopicColors_r24_Color 
{
	return [UIColor colorWithRed:0.949020 green:0.458824 blue:0.474510 alpha:1.0];
};

+(UIColor *)CopicColors_g05_Color 
{
	return [UIColor colorWithRed:0.411765 green:0.752941 blue:0.482353 alpha:1.0];
};

+(UIColor *)CopicColors_c0_Color 
{
	return [UIColor colorWithRed:0.878431 green:0.905882 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_r85_Color 
{
	return [UIColor colorWithRed:0.827451 green:0.415686 blue:0.576471 alpha:1.0];
};

+(UIColor *)CopicColors_c1_Color 
{
	return [UIColor colorWithRed:0.854902 green:0.890196 blue:0.909804 alpha:1.0];
};

+(UIColor *)CopicColors_b24_Color 
{
	return [UIColor colorWithRed:0.541176 green:0.807843 blue:0.952941 alpha:1.0];
};

+(UIColor *)CopicColors_c2_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.843137 blue:0.866667 alpha:1.0];
};

+(UIColor *)CopicColors_r56_Color 
{
	return [UIColor colorWithRed:0.823529 green:0.486275 blue:0.584314 alpha:1.0];
};

+(UIColor *)CopicColors_c3_Color 
{
	return [UIColor colorWithRed:0.756863 green:0.800000 blue:0.823529 alpha:1.0];
};

+(UIColor *)CopicColors_n10_Color 
{
	return [UIColor colorWithRed:0.192157 green:0.184314 blue:0.188235 alpha:1.0];
};

+(UIColor *)CopicColors_g07_Color 
{
	return [UIColor colorWithRed:0.482353 green:0.772549 blue:0.462745 alpha:1.0];
};

+(UIColor *)CopicColors_rv06_Color 
{
	return [UIColor colorWithRed:0.952941 green:0.525490 blue:0.686275 alpha:1.0];
};

+(UIColor *)CopicColors_c4_Color 
{
	return [UIColor colorWithRed:0.572549 green:0.627451 blue:0.670588 alpha:1.0];
};

+(UIColor *)CopicColors_rv19_Color 
{
	return [UIColor colorWithRed:0.823529 green:0.407843 blue:0.666667 alpha:1.0];
};

+(UIColor *)CopicColors_b26_Color 
{
	return [UIColor colorWithRed:0.396078 green:0.701961 blue:0.890196 alpha:1.0];
};

+(UIColor *)CopicColors_r27_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.313726 blue:0.384314 alpha:1.0];
};

+(UIColor *)CopicColors_c5_Color 
{
	return [UIColor colorWithRed:0.572549 green:0.627451 blue:0.670588 alpha:1.0];
};

+(UIColor *)CopicColors_y00_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.992157 blue:0.874510 alpha:1.0];
};

+(UIColor *)CopicColors_yg97_Color 
{
	return [UIColor colorWithRed:0.584314 green:0.560784 blue:0.011765 alpha:1.0];
};

+(UIColor *)CopicColors_c6_Color 
{
	return [UIColor colorWithRed:0.388235 green:0.439216 blue:0.474510 alpha:1.0];
};

+(UIColor *)CopicColors_r0000_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.952941 blue:0.937255 alpha:1.0];
};

+(UIColor *)CopicColors_g99_Color 
{
	return [UIColor colorWithRed:0.372549 green:0.494118 blue:0.227451 alpha:1.0];
};

+(UIColor *)CopicColors_c7_Color 
{
	return [UIColor colorWithRed:0.388235 green:0.439216 blue:0.474510 alpha:1.0];
};

+(UIColor *)CopicColors_g09_Color 
{
	return [UIColor colorWithRed:0.478431 green:0.768627 blue:0.396078 alpha:1.0];
};

+(UIColor *)CopicColors_bg93_Color 
{
	return [UIColor colorWithRed:0.729412 green:0.756863 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_yr61_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.854902 blue:0.768627 alpha:1.0];
};

+(UIColor *)CopicColors_r89_Color 
{
	return [UIColor colorWithRed:0.490196 green:0.168627 blue:0.258824 alpha:1.0];
};

+(UIColor *)CopicColors_c8_Color 
{
	return [UIColor colorWithRed:0.325490 green:0.364706 blue:0.400000 alpha:1.0];
};

+(UIColor *)CopicColors_b28_Color 
{
	return [UIColor colorWithRed:0.098039 green:0.427451 blue:0.713726 alpha:1.0];
};

+(UIColor *)CopicColors_r59_Color 
{
	return [UIColor colorWithRed:0.717647 green:0.309804 blue:0.439216 alpha:1.0];
};

+(UIColor *)CopicColors_r29_Color 
{
	return [UIColor colorWithRed:0.929412 green:0.090196 blue:0.294118 alpha:1.0];
};

+(UIColor *)CopicColors_y02_Color 
{
	return [UIColor colorWithRed:0.964706 green:0.952941 blue:0.588235 alpha:1.0];
};

+(UIColor *)CopicColors_c9_Color 
{
	return [UIColor colorWithRed:0.235294 green:0.278431 blue:0.301961 alpha:1.0];
};

+(UIColor *)CopicColors_y32_Color 
{
	return [UIColor colorWithRed:0.976471 green:0.870588 blue:0.752941 alpha:1.0];
};

+(UIColor *)CopicColors_b29_Color 
{
	return [UIColor colorWithRed:0.003922 green:0.466667 blue:0.756863 alpha:1.0];
};

+(UIColor *)CopicColors_yg99_Color 
{
	return [UIColor colorWithRed:0.305882 green:0.415686 blue:0.082353 alpha:1.0];
};

+(UIColor *)CopicColors_y04_Color 
{
	return [UIColor colorWithRed:0.929412 green:0.898039 blue:0.337255 alpha:1.0];
};

+(UIColor *)CopicColors_yg61_Color 
{
	return [UIColor colorWithRed:0.839216 green:0.913725 blue:0.839216 alpha:1.0];
};

+(UIColor *)CopicColors_b0000_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.976471 blue:0.996078 alpha:1.0];
};

+(UIColor *)CopicColors_y35_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.847059 blue:0.474510 alpha:1.0];
};

+(UIColor *)CopicColors_y06_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.960784 blue:0.423529 alpha:1.0];
};

+(UIColor *)CopicColors_bg70_Color 
{
	return [UIColor colorWithRed:0.854902 green:0.925490 blue:0.933333 alpha:1.0];
};

+(UIColor *)CopicColors_e50_Color 
{
	return [UIColor colorWithRed:0.956863 green:0.921569 blue:0.941176 alpha:1.0];
};

+(UIColor *)CopicColors_bg96_Color 
{
	return [UIColor colorWithRed:0.505882 green:0.635294 blue:0.568627 alpha:1.0];
};

+(UIColor *)CopicColors_e81_Color 
{
	return [UIColor colorWithRed:0.941176 green:0.901961 blue:0.760784 alpha:1.0];
};

+(UIColor *)CopicColors_e51_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.925490 blue:0.839216 alpha:1.0];
};

+(UIColor *)CopicColors_e21_Color 
{
	return [UIColor colorWithRed:0.992157 green:0.886275 blue:0.780392 alpha:1.0];
};

+(UIColor *)CopicColors_y38_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.823529 blue:0.454902 alpha:1.0];
};

+(UIColor *)CopicColors_y08_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.949020 blue:0.000000 alpha:1.0];
};

+(UIColor *)CopicColors_yg63_Color 
{
	return [UIColor colorWithRed:0.627451 green:0.792157 blue:0.635294 alpha:1.0];
};

+(UIColor *)CopicColors_yr65_Color 
{
	return [UIColor colorWithRed:0.980392 green:0.682353 blue:0.376471 alpha:1.0];
};

+(UIColor *)CopicColors_e53_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.874510 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_e23_Color 
{
	return [UIColor colorWithRed:0.925490 green:0.792157 blue:0.694118 alpha:1.0];
};

+(UIColor *)CopicColors_bg72_Color 
{
	return [UIColor colorWithRed:0.454902 green:0.721569 blue:0.733333 alpha:1.0];
};

+(UIColor *)CopicColors_e84_Color 
{
	return [UIColor colorWithRed:0.682353 green:0.623529 blue:0.501961 alpha:1.0];
};

+(UIColor *)CopicColors_v20_Color 
{
	return [UIColor colorWithRed:0.886275 green:0.878431 blue:0.929412 alpha:1.0];
};

+(UIColor *)CopicColors_y0000_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.996078 blue:0.956863 alpha:1.0];
};

+(UIColor *)CopicColors_e55_Color 
{
	return [UIColor colorWithRed:0.945098 green:0.874510 blue:0.725490 alpha:1.0];
};

+(UIColor *)CopicColors_e25_Color 
{
	return [UIColor colorWithRed:0.823529 green:0.643137 blue:0.509804 alpha:1.0];
};

+(UIColor *)CopicColors_yr0000_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.952941 blue:0.898039 alpha:1.0];
};

+(UIColor *)CopicColors_bv31_Color 
{
	return [UIColor colorWithRed:0.917647 green:0.905882 blue:0.949020 alpha:1.0];
};

+(UIColor *)CopicColors_v22_Color 
{
	return [UIColor colorWithRed:0.698039 green:0.694118 blue:0.815686 alpha:1.0];
};

+(UIColor *)CopicColors_bg99_Color 
{
	return [UIColor colorWithRed:0.431373 green:0.607843 blue:0.529412 alpha:1.0];
};

+(UIColor *)CopicColors_e87_Color 
{
	return [UIColor colorWithRed:0.435294 green:0.376471 blue:0.301961 alpha:1.0];
};

+(UIColor *)CopicColors_e57_Color 
{
	return [UIColor colorWithRed:0.694118 green:0.521569 blue:0.345098 alpha:1.0];
};

+(UIColor *)CopicColors_e27_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.462745 blue:0.388235 alpha:1.0];
};

+(UIColor *)CopicColors_yr68_Color 
{
	return [UIColor colorWithRed:0.952941 green:0.439216 blue:0.133333 alpha:1.0];
};

+(UIColor *)CopicColors_110_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.027451 blue:0.031373 alpha:1.0];
};

+(UIColor *)CopicColors_e89_Color 
{
	return [UIColor colorWithRed:0.352941 green:0.286275 blue:0.223529 alpha:1.0];
};

+(UIColor *)CopicColors_g20_Color 
{
	return [UIColor colorWithRed:0.929412 green:0.964706 blue:0.858824 alpha:1.0];
};

+(UIColor *)CopicColors_e59_Color 
{
	return [UIColor colorWithRed:0.603922 green:0.498039 blue:0.423529 alpha:1.0];
};

+(UIColor *)CopicColors_bv20_Color 
{
	return [UIColor colorWithRed:0.811765 green:0.858824 blue:0.945098 alpha:1.0];
};

+(UIColor *)CopicColors_e29_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.274510 blue:0.211765 alpha:1.0];
};

+(UIColor *)CopicColors_bg75_Color 
{
	return [UIColor colorWithRed:0.349020 green:0.568627 blue:0.556863 alpha:1.0];
};

+(UIColor *)CopicColors_v25_Color 
{
	return [UIColor colorWithRed:0.521569 green:0.498039 blue:0.678431 alpha:1.0];
};

+(UIColor *)CopicColors_yg41_Color 
{
	return [UIColor colorWithRed:0.835294 green:0.921569 blue:0.831373 alpha:1.0];
};

+(UIColor *)CopicColors_yg67_Color 
{
	return [UIColor colorWithRed:0.505882 green:0.749020 blue:0.549020 alpha:1.0];
};

+(UIColor *)CopicColors_yr30_Color 
{
	return [UIColor colorWithRed:0.996078 green:0.949020 blue:0.854902 alpha:1.0];
};

+(UIColor *)CopicColors_g21_Color 
{
	return [UIColor colorWithRed:0.768627 green:0.894118 blue:0.803922 alpha:1.0];
};

@end