//
// UIColor+HTML1.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
//
//

#import "UIColor+HTML1.h"

@implementation UIColor (HTML1)

+(UIColor *)HTML1_MediumOrchid_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.666667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML1_PaleGoldenRod_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_OrangeRed_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML1_GhostWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.533333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_SteelBlue_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.400000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_MediumTurquoise_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.533333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_PaleTurquoise_Color 
{
	return [UIColor colorWithRed:0.666667 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_DarkKhaki_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_BlueViolet_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.666667 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML1_Violet_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_IndianRed_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML1_FireBrick_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.133333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML1_SaddleBrown_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML1_DarkOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_Chocolate_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.133333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_SpringGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_MediumVioletRed_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.466667 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML1_SlateBlue_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.666667 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML1_MediumPurple_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.200000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML1_Pink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_LightGreen_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_Orchid_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.666667 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML1_Aquamarine_Color 
{
	return [UIColor colorWithRed:0.466667 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkOrchid_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.600000 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML1_Magenta_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkGoldenRod_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.533333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_FloralWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_SeaGreen_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.933333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_DarkViolet_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.266667 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_AntiqueWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_MidnightBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.600000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML1_RosyBrown_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.800000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_DarkTurquoise_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_Purple_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_PaleVioletRed_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML1_CornflowerBlue_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.266667 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML1_LimeGreen_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.133333 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_LightSteelBlue_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_Gold_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_Indigo_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.733333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Bisque_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_Beige_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Chartreuse_Color 
{
	return [UIColor colorWithRed:0.466667 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_PaleGreen_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.533333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_ForestGreen_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.133333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_Coral_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)HTML1_Red_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Silver_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_Cyan_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_RoyalBlue_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.066667 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_LawnGreen_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.800000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkBlue_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Orange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML1_MediumAquaMarine_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_SeaShell_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_LightBlue_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.866667 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_LightPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_Cornsilk_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Black_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Tomato_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_LemonChiffon_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Ivory_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Plum_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML1_Snow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_PowderBlue_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_Tan_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.133333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_Linen_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_LightSlateGray_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.466667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_Azure_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_White_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkGray_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.600000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML1_MintCream_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_LightCyan_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_LightSkyBlue_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_DeepSkyBlue_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_SkyBlue_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_Fuchsia_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_HoneyDew_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkRed_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_LavenderBlush_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Blue_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Gray_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_Navy_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Wheat_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_LightSalmon_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML1_DarkSlateGray_Color 
{
	return [UIColor colorWithRed:0.133333 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)HTML1_DarkCyan_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_LightCoral_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_GoldenRod_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.666667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML1_OldLace_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Yellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_MediumSeaGreen_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.800000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_SlateGray_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_NavajoWhite_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_PapayaWhip_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_PeachPuff_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_MistyRose_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_Turquoise_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_DarkMagenta_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.733333 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_Teal_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_Peru_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_MediumSlateBlue_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_DimGray_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.600000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_Crimson_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.800000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML1_Lavender_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.400000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_YellowGreen_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.666667 blue:0.800000 alpha:1.0];
};

+(UIColor *)HTML1_MediumSpringGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Thistle_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.533333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_DarkOliveGreen_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.333333 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_DarkSeaGreen_Color 
{
	return [UIColor colorWithRed:0.533333 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_Brown_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.333333 blue:0.133333 alpha:1.0];
};

+(UIColor *)HTML1_AliceBlue_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Salmon_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_LightYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkSalmon_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.600000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML1_Sienna_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.000000 blue:0.333333 alpha:1.0];
};

+(UIColor *)HTML1_Lime_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_DodgerBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.933333 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML1_Maroon_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_DarkSlateBlue_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.533333 blue:0.200000 alpha:1.0];
};

+(UIColor *)HTML1_BlanchedAlmond_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_BurlyWood_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.933333 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_LightSeaGreen_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)HTML1_Green_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_SandyBrown_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.266667 blue:0.666667 alpha:1.0];
};

+(UIColor *)HTML1_Gainsboro_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.800000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_Aqua_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_HotPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_MediumBlue_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)HTML1_WhiteSmoke_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.333333 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_Khaki_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_Moccasin_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)HTML1_Olive_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_OliveDrab_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.733333 blue:0.533333 alpha:1.0];
};

+(UIColor *)HTML1_LightGoldenRodYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)HTML1_LightGray_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.200000 blue:0.866667 alpha:1.0];
};

+(UIColor *)HTML1_DeepPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.066667 alpha:1.0];
};

+(UIColor *)HTML1_DarkGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)HTML1_CadetBlue_Color 
{
	return [UIColor colorWithRed:0.333333 green:1.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)HTML1_GreenYellow_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.866667 blue:1.000000 alpha:1.0];
};

@end