//
// UIColor+Crayola.m
//
//
// Generated by https://github.com/mihaelamj/uicolor-category-maker
//
//

#import "UIColor+Crayola.h"

@implementation UIColor (Crayola)

+(UIColor *)Crayola_Dandelion_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_MangoTango_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_PineGreen_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.333333 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_OrangeRed_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.133333 alpha:1.0];
};

+(UIColor *)Crayola_WildStrawberry_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Cornflower_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.666667 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_AtomicTangerine_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_CottonCandy_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_Sunglow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_BlueViolet_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.200000 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_Manatee_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.466667 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_GreenBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.066667 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_WildWatermelon_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_PurplePizzazz_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.933333 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_VioletBlue_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.133333 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Cerulean_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_SpringGreen_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.800000 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_BurntOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Orchid_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.400000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_BlizzardBlue_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.800000 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_OrangeYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.533333 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_Aquamarine_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.533333 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_Magenta_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.400000 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_RawUmber_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.066667 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_LaserLemon_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.933333 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_GrannySmithApple_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.533333 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_SeaGreen_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.200000 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_UnmellowYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_Maize_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.866667 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_RawSienna_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.400000 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_PiggyPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_YellowOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_PurpleMountainsMajesty_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.866667 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_Mauvelous_Color 
{
	return [UIColor colorWithRed:0.933333 green:1.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_MidnightBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.666667 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_LemonYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_VividTangerine_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Razzmatazz_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.200000 blue:0.133333 alpha:1.0];
};

+(UIColor *)Crayola_TealBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.533333 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Shadow_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.666667 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Gold_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.466667 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_Blush_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.933333 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_RazzleDazzleRose_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Indigo_Color 
{
	return [UIColor colorWithRed:0.333333 green:0.866667 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_ForestGreen_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Orange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Red_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.933333 blue:0.133333 alpha:1.0];
};

+(UIColor *)Crayola_Silver_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_Inchworm_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.133333 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_CarnationPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Fern_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.066667 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_RoyalPurple_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.533333 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_Black_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)Crayola_RedOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_Plum_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.933333 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Mahogany_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Tan_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_FuzzyWuzzy_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.800000 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_Beaver_Color 
{
	return [UIColor colorWithRed:0.600000 green:1.000000 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_BananaMania_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.666667 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_WildBlueYonder_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.133333 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_NeonCarrot_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Shamrock_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.333333 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_JungleGreen_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.733333 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_Canary_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_HotMagenta_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.066667 alpha:1.0];
};

+(UIColor *)Crayola_Melon_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_MacaroniandCheese_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_Tumbleweed_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.933333 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Timberwolf_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.733333 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_White_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_TickleMePink_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_SkyBlue_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_Scarlet_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.133333 alpha:1.0];
};

+(UIColor *)Crayola_Almond_Color 
{
	return [UIColor colorWithRed:0.933333 green:1.000000 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_Fuchsia_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.200000 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_OutrageousOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_PacificBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.800000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Copper_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_Blue_Color 
{
	return [UIColor colorWithRed:0.066667 green:1.000000 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Gray_Color 
{
	return [UIColor colorWithRed:0.600000 green:0.333333 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_Bittersweet_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_RadicalRed_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_PurpleHeart_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.266667 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_PinkFlamingo_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Denim_Color 
{
	return [UIColor colorWithRed:0.133333 green:0.733333 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_Chestnut_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.800000 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_Goldenrod_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_RobinsEggBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_TropicalRainForest_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.466667 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_CaribbeanGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_BrickRed_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.733333 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Yellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_ScreaminGreen_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.400000 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_Asparagus_Color 
{
	return [UIColor colorWithRed:0.533333 green:0.466667 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_BlueBell_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.133333 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_JazzberryJam_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.666667 blue:0.200000 alpha:1.0];
};

+(UIColor *)Crayola_VioletRed_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.466667 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_Apricot_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_SunsetOrange_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.866667 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_YellowGreen_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.333333 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_Lavender_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.800000 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_BlueGreen_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_BurntSienna_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.666667 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Thistle_Color 
{
	return [UIColor colorWithRed:0.933333 green:0.733333 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_NavyBlue_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.600000 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_Brown_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.266667 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_VioletPurple_Color 
{
	return [UIColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.0];
};

+(UIColor *)Crayola_OuterSpace_Color 
{
	return [UIColor colorWithRed:0.266667 green:0.066667 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_ShockingPink_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.733333 blue:0.466667 alpha:1.0];
};

+(UIColor *)Crayola_MountainMeadow_Color 
{
	return [UIColor colorWithRed:0.200000 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_Salmon_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_AntiqueBrass_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_Cerise_Color 
{
	return [UIColor colorWithRed:0.866667 green:0.866667 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_Maroon_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.533333 blue:0.200000 alpha:1.0];
};

+(UIColor *)Crayola_PinkSherbert_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.466667 blue:0.533333 alpha:1.0];
};

+(UIColor *)Crayola_DesertSand_Color 
{
	return [UIColor colorWithRed:0.933333 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_Green_Color 
{
	return [UIColor colorWithRed:0.066667 green:0.800000 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_Sepia_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.333333 blue:0.400000 alpha:1.0];
};

+(UIColor *)Crayola_Periwinkle_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.333333 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_TurquoiseBlue_Color 
{
	return [UIColor colorWithRed:0.466667 green:0.466667 blue:0.866667 alpha:1.0];
};

+(UIColor *)Crayola_MagicMint_Color 
{
	return [UIColor colorWithRed:0.666667 green:0.666667 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_Peach_Color 
{
	return [UIColor colorWithRed:1.000000 green:1.000000 blue:0.800000 alpha:1.0];
};

+(UIColor *)Crayola_RedViolet_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.000000 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_ElectricLime_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.933333 blue:1.000000 alpha:1.0];
};

+(UIColor *)Crayola_Mulberry_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.333333 blue:0.266667 alpha:1.0];
};

+(UIColor *)Crayola_BlueGray_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.400000 blue:0.600000 alpha:1.0];
};

+(UIColor *)Crayola_Eggplant_Color 
{
	return [UIColor colorWithRed:0.400000 green:0.933333 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_Wisteria_Color 
{
	return [UIColor colorWithRed:0.800000 green:0.866667 blue:0.666667 alpha:1.0];
};

+(UIColor *)Crayola_VividViolet_Color 
{
	return [UIColor colorWithRed:0.533333 green:1.000000 blue:0.333333 alpha:1.0];
};

+(UIColor *)Crayola_CadetBlue_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.000000 blue:0.733333 alpha:1.0];
};

+(UIColor *)Crayola_GreenYellow_Color 
{
	return [UIColor colorWithRed:1.000000 green:0.000000 blue:0.933333 alpha:1.0];
};

+(UIColor *)Crayola_OliveGreen_Color 
{
	return [UIColor colorWithRed:0.733333 green:0.666667 blue:0.733333 alpha:1.0];
};

@end